{
	 "description":"ADME_PAYMENT_EDR",
	 "sqlStatements": [
	  {
		"sql"      	:"
select
	concat(substring(a.`month` , 1, 4), substring(a.`month` , 6, 2)) as mo_key,
	substring(a.`month` , 12, 2) as hour_key,
	CAST(NULL AS string) AS UUID,
	a.payment_id as PYMT_REF_NBR,
	CAST(a.RECEIPT_DATE AS timestamp) AS PYMT_DT,
	CASE
		WHEN a.PAYMENT_TYPE = '' THEN CAST(NULL AS string)
		ELSE a.PAYMENT_TYPE
	end as PYMT_MTHD_TYP_CD,
	CAST(NULL AS string) AS PYMT_CHNL_TYP_CD,
	CAST(NULL AS integer) AS PYMT_CHNL_KEY,
	CAST(NULL AS string) AS PYMT_CHNL_CD,
	CAST(NULL AS bigint) AS PYMT_OPRTR_KEY,
	CAST(NULL AS string) AS PYMT_OPRTR_CD,
	CAST(NULL AS integer) AS PYMT_BSNS_OUTLET_KEY,
	CAST(NULL AS string) AS PYMT_BSNS_OUTLET_CD,
	CAST(NULL AS string) AS THIRD_PRTY_PYMT_TXN_REF_NBR,
	CASE
		WHEN a.STATUS = '' THEN CAST(NULL AS string)
		ELSE a.STATUS
	end as PYMT_STAT_CD,
	CASE
		WHEN a.ADJ_REASON = '' THEN CAST(NULL AS string)
		ELSE a.ADJ_REASON
	end as PYMT_STAT_RSN_CD,
	CAST(NULL AS string) AS FILE_NAME,
	CAST(NULL AS timestamp) AS FILE_DT,
	CAST(NULL AS string) AS FILE_PREFIX_CD,
	CAST(NULL AS timestamp) AS REC_PROCESS_DT,
	CAST(NULL AS string) AS SWITCH_CD,
	CAST(NULL AS decimal(27,
	0)) AS ACCT_SRVC_INSTANCE_KEY,
	CAST(NULL AS string) AS SERVICE_NBR,
	CAST(NULL AS decimal(27,
	0)) AS ACCT_KEY,
	CAST(NULL AS decimal(27,
	0)) AS BILLABLE_ACCT_KEY,
	CAST(NULL AS string) AS BILL_GRP_CD,
	CAST(b.CUST_KEY AS decimal(27,
	0)) AS CUST_KEY,
	CASE
		WHEN b.CUST_TYP_CD = '' THEN CAST(NULL AS string)
		ELSE b.CUST_TYP_CD
	end as CUST_TYP_CD,
	CAST(NULL AS string) AS NTWK_QOS_GRP_CD,
	CAST(NULL AS timestamp) AS ACCT_ACTIVATION_DT,
	CAST(NULL AS timestamp) AS ACCT_CBS_ACTIVATION_DT,
	CAST(NULL AS string) AS ACCT_LFCYCL_STAT_CD,
	CAST(NULL AS timestamp) AS SRVC_ACTIVATION_DT,
	CAST(NULL AS timestamp) AS SRVC_CBS_ACTIVATION_DT,
	CAST(NULL AS string) AS SRVC_LFCYCL_STAT_CD,
	CAST(NULL AS integer) AS PROD_LINE_KEY,
	CAST(NULL AS bigint) AS USAGE_PLAN_KEY,
	CAST(NULL AS string) AS USAGE_PLAN_CD,
	CAST(NULL AS string) AS USAGE_PLAN_TYP_CD,
	'VND' as CRNCY_CD,
	CAST(a.PAYMENT_AMOUNT AS decimal(27,
	8)) AS PYMT_AMT,
	CAST(NULL AS decimal(27,
	8)) AS MAIN_BAL_AMT_BEFR_PYMT,
	CAST(NULL AS decimal(27,
	8)) AS MAIN_BAL_AMT_AFTR_PYMT,
	CAST(NULL AS decimal(27,
	8)) AS PYMT_COST_AMT,
	CAST(NULL AS string) AS PYMT_ADD_INFO,
	CAST(NULL AS string) AS AUTH_CD,
	CAST(NULL AS timestamp) AS AUTH_DT,
	CAST(NULL AS string) AS AUTH_AUTHORITY_NAME,
	CAST(NULL AS string) AS BANK_GEO_CNTRY_CD,
	CASE
		WHEN a.BANK_CODE = '' THEN CAST(NULL AS string)
		ELSE a.BANK_CODE
	end as SWIFT,
	CASE
		WHEN a.ACCOUNT_NO = '' THEN CAST(NULL AS string)
		ELSE a.ACCOUNT_NO
	end as BANK_ACCT_NBR,
	CAST(NULL AS string) AS BANK_CARD_NBR,
	CAST(NULL AS string) AS BANK_CARD_TYP_CD,
	CAST(NULL AS string) AS CHEQUE_NBR,
	CAST(NULL AS timestamp) AS CHEQUE_DT,
	CAST(NULL AS decimal(27,
	8)) AS CHEQUE_AMT,
	CAST(NULL AS timestamp) AS CHEQUE_RETURN_DT,
	CAST(NULL AS decimal(27,
	8)) AS ADDR_LAT,
	CAST(NULL AS decimal(27,
	8)) AS ADDR_LON,
	CAST(NULL AS bigint) AS CELL_KEY,
	CAST(NULL AS string) AS CELL_CD,
	CAST(NULL AS bigint) AS CELL_SITE_KEY,
	CAST(NULL AS string) AS CELL_SITE_CD,
	CAST(NULL AS bigint) AS NTWK_MGNT_CENTRE_KEY,
	CAST(NULL AS string) AS NTWK_MGNT_CENTRE_CD,
	CAST(b.BSNS_RGN_KEY AS bigint) AS BSNS_RGN_KEY,
	CASE
		WHEN b.BSNS_RGN_CD = '' THEN CAST(NULL AS string)
		ELSE b.BSNS_RGN_CD
	end as BSNS_RGN_CD,
	CAST(b.BSNS_CLUSTER_KEY AS bigint) AS BSNS_CLUSTER_KEY,
	CASE
		WHEN b.BSNS_CLUSTER_CD = '' THEN CAST(NULL AS string)
		ELSE b.BSNS_CLUSTER_CD
	end as BSNS_CLUSTER_CD,
	CAST(b.BSNS_MINICLUSTER_KEY AS bigint) AS BSNS_MINICLUSTER_KEY,
	CASE
		WHEN b.BSNS_MINICLUSTER_CD = '' THEN CAST(NULL AS string)
		ELSE b.BSNS_MINICLUSTER_CD
	end as BSNS_MINICLUSTER_CD,
	CAST(b.GEO_CNTRY_KEY AS bigint) AS GEO_CNTRY_KEY,
	CASE
		WHEN b.GEO_CNTRY_CD = '' THEN CAST(NULL AS string)
		ELSE b.GEO_CNTRY_CD
	end as GEO_CNTRY_CD,
	CAST(b.GEO_STATE_KEY AS bigint) AS GEO_STATE_KEY,
	CASE
		WHEN b.GEO_STATE_CD = '' THEN CAST(NULL AS string)
		ELSE b.GEO_STATE_CD
	end as GEO_STATE_CD,
	CAST(b.GEO_DSTRCT_KEY AS bigint) AS GEO_DSTRCT_KEY,
	CASE
		WHEN b.GEO_DSTRCT_CD = '' THEN CAST(NULL AS string)
		ELSE b.GEO_DSTRCT_CD
	end as GEO_DSTRCT_CD,
	CAST(b.GEO_CITY_KEY AS bigint) AS GEO_CITY_KEY,
	CASE
		WHEN b.GEO_CITY_CD = '' THEN CAST(NULL AS string)
		ELSE b.GEO_CITY_CD
	end as GEO_CITY_CD,
	CAST(b.ACQSTN_DT AS timestamp) AS ACQSTN_DT,
	CAST(b.ACQSTN_BSNS_OUTLET_KEY AS bigint) AS ACQSTN_BSNS_OUTLET_KEY,
	CASE
		WHEN b.ACQSTN_BSNS_OUTLET_CD = '' THEN CAST(NULL AS string)
		ELSE b.ACQSTN_BSNS_OUTLET_CD
	end as ACQSTN_BSNS_OUTLET_CD,
	CAST(NULL AS decimal(12,
	4)) AS LOYALTY_RANK_SCORE,
	CAST(NULL AS timestamp) AS LOYALTY_SCORE_DT,
	CAST(NULL AS decimal(12,
	4)) AS CREDIT_SCORE,
	CAST(NULL AS string) AS CREDIT_CLASS_CD,
	CAST(NULL AS string) AS CREDIT_SCORE_METHOD,
	CAST(NULL AS timestamp) AS CREDIT_SCORE_DT,
	CAST(NULL AS integer) AS RISK_IND,
	CAST(NULL AS string) AS ACCT_SEGMENT_CD,
	CAST(NULL AS string) AS ACCT_SEGMENT_DT,
	CAST(NULL AS string) AS CMPGN_CD,
	CAST(24 AS bigint) AS SRC_SYS_KEY,
	'BILLING_GOLD' as SRC_SYS_CD,
	current_timestamp() AS LOAD_DT,
	'1' as CURR_IND,
	CAST(1 AS integer) AS WRHS_ID
from
	mbf_datalake.b4_payment a
left join mbf_bigdata.admr_customer b on
	cast(b.cust_key as string) = concat('2', a.cust_id)
	and b.day_key = '$day_key'
where
	a.day_key = '$day_key'
",
		"tempTable"  : "ADME_PAYMENT_EDR_TMP",
		"countSourceRecord":"1"
	  }   	  
	]
}