{
	 "description":"ADME_RATED_OFFER_SBRP_EDR",
	 "sqlStatements": [
	 {
		"sql"      : "
						SELECT * FROM
						(
						  SELECT 
							ROW_NUMBER() OVER (PARTITION BY C4.CELL_KEY_4G ORDER BY C4.cell_gci_cd DESC) AS ROWNUM, C4.* 
						  FROM 
						  (
							SELECT      
							  CASE WHEN CELL_TYP_CD = '4G' THEN CONCAT(SPLIT(CELL_KEY,'[\\-]')[0],'-',SPLIT(CELL_KEY,'[\\-]')[1],'-',SPLIT(CELL_KEY,'[\\-]')[3],'-',SPLIT(CELL_KEY,'[\\-]')[4])
							  ELSE CELL_KEY END AS CELL_KEY_4G,
							  *
							FROM MBF_BIGDATA.ADMR_CELL WHERE DAY_KEY = '$day_key' AND nvl(CELL_DSCR,'') NOT LIKE '%TEST%'
						  ) C4
						) X WHERE X.ROWNUM = 1
					",
		"tempTable" : "CELL_4G_STD",
		"countSourceRecord" : "0",
		"description": "STG_CDR_IN_ENRICH enrich du lieu NON_CELL ca tu nguon flexi, cell_4G tren flexi co dang mcc-mnc-nodebid-cell, nen khi join cell_4g vao admr_cell phai bo TAC"
	 },		 	 
	 {
	 "sql" : "
				SELECT  A.OFFER_KEY , A.OFFER_CD , A.OFFER_NAME , A.OFFER_TYP_CD, A.PROD_LINE_KEY, A.SBRP_RC_AMT, A.SBRP_NRC_AMT, A.ADD_INFO,
				CONCAT_WS(',', COLLECT_SET(B.USAGE_TYP_CD)) AS USAGE_TYP_CD,
				CASE WHEN CONCAT_WS(',', COLLECT_SET(B.USAGE_TYP_CD)) = 'VOICE' THEN 'VOICE_PACK_SBRP' 
						WHEN CONCAT_WS(',', COLLECT_SET(B.USAGE_TYP_CD)) = 'SMS' THEN 'SMS_PACK_SBRP' 
						WHEN CONCAT_WS(',', COLLECT_SET(B.USAGE_TYP_CD))='DATA' THEN 'DATA_PACK_SBRP' 
						ELSE 'BUNDLE_PACK_SBRP' 
				END AS EVT_CTGRY_CD
				FROM MBF_BIGDATA.ADMR_OFFER A
				LEFT  JOIN MBF_BIGDATA.ADMR_OFFER_RELATION B ON A.OFFER_KEY =B.PARENT_OFFER_KEY AND B.DAY_KEY = '$day_key' AND B.USAGE_TYP_CD IS NOT NULL
				WHERE A.OFFER_TYP_CD = 'PACKAGE' AND A.DAY_KEY = '$day_key'
				GROUP BY A.OFFER_KEY,A.OFFER_CD,A.OFFER_NAME, A.OFFER_TYP_CD, A.PROD_LINE_KEY, A.SBRP_RC_AMT, A.SBRP_NRC_AMT, A.ADD_INFO
			",
	 "tempTable"  : "OFFER_TMP",
	 "countSourceRecord":"0"		
	 },
	 {
	 "sql" : "
				SELECT OFFER_KEY , OFFER_CD , OFFER_NAME , OFFER_TYP_CD, PROD_LINE_KEY, SBRP_RC_AMT, SBRP_NRC_AMT, USAGE_TYP_CD, EVT_CTGRY_CD
				FROM
				(
					SELECT  ROW_NUMBER() OVER  (PARTITION BY A.offer_cd ORDER BY A.offer_cd) as row_num, 
					A.OFFER_KEY , A.OFFER_CD , A.OFFER_NAME , A.OFFER_TYP_CD, A.PROD_LINE_KEY, A.SBRP_RC_AMT, A.SBRP_NRC_AMT,
					CONCAT_WS(',', COLLECT_SET(B.USAGE_TYP_CD)) AS USAGE_TYP_CD,
					CASE WHEN CONCAT_WS(',', COLLECT_SET(B.USAGE_TYP_CD)) = 'VOICE' THEN 'VOICE_PACK_SBRP' 
							WHEN CONCAT_WS(',', COLLECT_SET(B.USAGE_TYP_CD)) = 'SMS' THEN 'SMS_PACK_SBRP' 
							WHEN CONCAT_WS(',', COLLECT_SET(B.USAGE_TYP_CD))='DATA' THEN 'DATA_PACK_SBRP' 
							ELSE 'BUNDLE_PACK_SBRP' 
					END AS EVT_CTGRY_CD
					FROM MBF_BIGDATA.ADMR_OFFER A
					LEFT  JOIN MBF_BIGDATA.ADMR_OFFER_RELATION B ON A.OFFER_KEY =B.PARENT_OFFER_KEY AND B.DAY_KEY = '$day_key' AND B.USAGE_TYP_CD IS NOT NULL
					WHERE A.OFFER_TYP_CD = 'PACKAGE' AND A.DAY_KEY = '$day_key'
					GROUP BY A.OFFER_KEY,A.OFFER_CD,A.OFFER_NAME, A.OFFER_TYP_CD, A.PROD_LINE_KEY, A.SBRP_RC_AMT, A.SBRP_NRC_AMT
				) X WHERE X.ROW_NUM = 1
			",
	 "tempTable"  : "OFFER_TMP_ROWNUMBER",
	 "countSourceRecord":"0"		
	 },
	 {
	 "sql" : "
		 SELECT 
			 X.*, D.PROD_CD, D.PROD_KEY
			FROM (
				SELECT
					mt.TREE_ID,
					icc.*,
					ROW_NUMBER () OVER (PARTITION BY icc.CALL_STA_TIME,icc.CALLING_ISDN,icc.TRANSACTION_DESCRIPTION, icc.ftp_filename, icc.stt,icc.ITEM_ID,icc.SUB_ITEM_ID, mt.ITEM_ID_DTTT, mt.SUB_ITEM_ID ORDER BY mt.INCLUDE_SUB_ITEM_ID DESC, mt.EFFECT_FROM DESC) ROW_NUM_SUB,
					ROW_NUMBER () OVER (PARTITION BY icc.CALL_STA_TIME,icc.CALLING_ISDN,icc.TRANSACTION_DESCRIPTION, icc.ftp_filename, icc.stt,icc.ITEM_ID,icc.SUB_ITEM_ID,mt.ITEM_ID_DTTT ORDER BY mt.EFFECT_FROM DESC) ROW_NUM
				FROM MBF_STAGE.STG_CDR_IN_ENRICH icc
				LEFT OUTER JOIN MBF_DATALAKE.MAP_TREE mt
					ON FROM_UNIXTIME(UNIX_TIMESTAMP(CONCAT(SUBSTRING(mt.EFFECT_FROM,0,4),SUBSTRING(mt.EFFECT_FROM,6,2),'01'), 'yyyyMMdd')) <= FROM_UNIXTIME(UNIX_TIMESTAMP('$day_key', 'yyyyMMdd'))
					AND FROM_UNIXTIME(UNIX_TIMESTAMP('$day_key', 'yyyyMMdd')) < CASE WHEN (mt.EFFECT_UNTIL IS NULL OR mt.EFFECT_UNTIL = '') THEN FROM_UNIXTIME(UNIX_TIMESTAMP('$day_key', 'yyyyMMdd')+1) 
					ELSE DATE_ADD(LAST_DAY(FROM_UNIXTIME(UNIX_TIMESTAMP(CONCAT(SUBSTRING(mt.EFFECT_UNTIL,0,4),SUBSTRING(mt.EFFECT_UNTIL,6,2),'01') , 'yyyyMMdd'))),1)  END
					AND NVL (mt.ITEM_ID_DTTT, '-1') = NVL (icc.ITEM_ID, '-1')
					AND ((mt.INCLUDE_SUB_ITEM_ID = '1' AND NVL (UPPER(mt.SUB_ITEM_ID), '-1') = NVL (UPPER (icc.SUB_ITEM_ID), '-1')) OR mt.INCLUDE_SUB_ITEM_ID = '0')
				
				WHERE 
				(
					(icc.call_type_ind = 'OTHER' AND icc.call_type in (176,177)) 
					OR (icc.CALL_TYPE = 415 
						and not ((nvl(icc.transaction_description,'') like 'UT%' and cast(SUBSTRING(icc.scratch_value,1,LENGTH(scratch_value)-2) as int) > 0)  or nvl(icc.transaction_description,'') like '%HU%'))
				)
				and icc.day_key = '$day_key'
			) X 
			LEFT JOIN MBF_BIGDATA.ADMR_PRODUCT D ON D.PROD_KEY = NVL(X.TREE_ID,'157')	 AND D.DAY_KEY = '$day_key'
			LEFT JOIN 
			(SELECT *, 
			ROW_NUMBER() OVER(PARTITION BY OFFER_CD ORDER BY OFFER_CD) AS ROW_NUM
			FROM MBF_BIGDATA.ADMR_OFFER WHERE DAY_KEY ='$day_key') F ON F.offer_cd = X.TRANSACTION_DESCRIPTION AND X.CALL_TYPE = 415  AND F.ROW_NUM = 1
			WHERE X.ROW_NUM_SUB = 1 AND X.ROW_NUM = 1 AND ((X.CALL_TYPE = 415 AND F.OFFER_KEY IS NOT NULL) OR (X.CALL_TYPE <> 415 AND F.OFFER_KEY IS NULL))
		",
	 "tempTable"  : "CDR_ICC_TMP",
	 "countSourceRecord":"0"		
	 }, 
	 
	  {
		"sql"      : "
						SELECT 
							cast(SUBSTR('$day_key',1,6)as INTEGER) 				 							as MO_KEY,
							cast(from_unixtime(unix_timestamp(nvl(a.call_sta_time,a.reg_datetime),'dd/MM/yyyy HH'),'HH') as INTEGER)  	  as hour_key,
							cast(NULL as string) 										 as uuid,
							cast(NULL as string) 										 as SBRP_REF_CD,
							cast(from_unixtime(unix_timestamp(nvl(a.call_sta_time,a.reg_datetime),'dd/MM/yyyy HH:mm:ss')) as timestamp) 							 as SBRP_DT,
							cast(from_unixtime(unix_timestamp(nvl(a.call_sta_time,a.reg_datetime),'dd/MM/yyyy HH:mm:ss')) as timestamp) 							 as BLLG_START_DT,
							a.FTP_FILENAME 												 as FILE_NAME,
							cast(NULL as timestamp) 									 as FILE_DT,
							cast(NULL as string) 										 as FILE_PREFIX_CD,
							cast(NULL as timestamp) 									 as REC_PROCESS_DT,
							cast(NULL as string) 										 as SWITCH_CD,
							cast(b.ACCT_SRVC_INSTANCE_KEY as DECIMAL(27,0)) 			 as ACCT_SRVC_INSTANCE_KEY,
							a.CALLING_ISDN 												 as SERVICE_NBR,
							cast(b.ACCT_KEY as DECIMAL(27,0)) 							 as ACCT_KEY,
							cast(b.BILLABLE_ACCT_KEY as DECIMAL(27,0)) 					 as BILLABLE_ACCT_KEY,
							cast(NULL as string) 										 as BILL_GRP_CD,
							cast(NULL as BIGINT) 										 as BILL_CYCLE_KEY,
							cast(b.CUST_KEY as DECIMAL(27,0)) 							 as CUST_KEY,
							b.CUST_TYP_CD,
							b.CORPORATE_IND,
							b.NTWK_QOS_GRP_CD,
							cast(b.ACTIVATION_DT as timestamp) 							 as ACCT_ACTIVATION_DT,
							cast(b.CBS_ACTIVATION_DT as timestamp) 						 as ACCT_CBS_ACTIVATION_DT,
							b.LFCYCL_STAT_CD 											 as ACCT_LFCYCL_STAT_CD,
							cast(b.ACTIVATION_DT as timestamp) 							 as SRVC_ACTIVATION_DT,
							cast(b.CBS_ACTIVATION_DT as timestamp) 						 as SRVC_CBS_ACTIVATION_DT,
							b.LFCYCL_STAT_CD 											 as SRVC_LFCYCL_STAT_CD,
							cast(b.PROD_LINE_KEY as INTEGER) 							 as PROD_LINE_KEY,
							cast(b.USAGE_PLAN_KEY  as BIGINT) 							 as USAGE_PLAN_KEY,
							b.USAGE_PLAN_CD 											 as USAGE_PLAN_CD,
							b.USAGE_PLAN_TYP_CD 										 as USAGE_PLAN_TYP_CD,
							cast(c.OFFER_KEY as BIGINT) 								 as OFFER_KEY,
							a.TRANSACTION_DESCRIPTION 									 as OFFER_CD,
							c.OFFER_TYP_CD 												 as OFFER_TYP_CD,
							CAST(NVL(A.TREE_ID,157)	 AS DECIMAL(20,0))	  	 				 as PROD_KEY,
							A.PROD_CD 													 as PROD_CD,
							A.ITEM_ID													 AS ITEM_KEY,
							A.SUB_ITEM_ID												 AS SUB_ITEM_CD,
							'SBRP' 							 							 as EVT_CLASS_CD,
							c.EVT_CTGRY_CD 												 as EVT_CTGRY_CD,
							CASE 
							WHEN c.EVT_CTGRY_CD = 'VOICE_PACK_SBRP' AND a.REG_CODE LIKE 'VASP%' THEN 'VOICE_PACK_RENEWAL'
							WHEN c.EVT_CTGRY_CD = 'VOICE_PACK_SBRP' AND a.REG_CODE NOT LIKE 'VASP%' THEN 'VOICE_PACK_ACTVTN'
							WHEN c.EVT_CTGRY_CD = 'DATA_PACK_SBRP' AND a.REG_CODE LIKE 'VASP%' THEN 'DATA_PACK_RENEWAL'
							WHEN c.EVT_CTGRY_CD = 'DATA_PACK_SBRP' AND a.REG_CODE NOT LIKE 'VASP%' THEN 'DATA_PACK_ACTVTN'
							WHEN c.EVT_CTGRY_CD = 'SMS_PACK_SBRP' AND a.REG_CODE LIKE 'VASP%' THEN 'SMS_PACK_RENEWAL'
							WHEN c.EVT_CTGRY_CD = 'SMS_PACK_SBRP' AND a.REG_CODE NOT LIKE 'VASP%' THEN 'SMS_PACK_ACTVTN'
							WHEN c.EVT_CTGRY_CD = 'BUNDLE_PACK_SBRP' AND a.REG_CODE NOT LIKE 'VASP%' THEN 'BUNDLE_PACK_RENEWAL'
							WHEN c.EVT_CTGRY_CD = 'BUNDLE_PACK_SBRP' AND a.REG_CODE LIKE 'VASP%' THEN 'BUNDLE_PACK_ACTVTN'
							ELSE 'UNKNOWN'
							END 														 as EVT_TYP_CD,
							'VND' 														 as CRNCY_CD,
							c.USAGE_TYP_CD												 as USAGE_TYP_CD,
							cast(NULL as string) 										 as SBRP_CHNL_TYP_CD,
							a.REG_CODE 									 				 as SOURCE_OF_SIGNUP_CD,
							cast(NULL as BIGINT) 										 as BSNS_OUTLET_KEY,
							cast(NULL as string) 										 as BSNS_OUTLET_CD,
							cast(NULL as string) 										 as BSNS_OUTLET_TYP_CD,
							cast(NULL as string) 										 as SALES_AGENT_ID,
							cast(from_unixtime(unix_timestamp(nvl(a.reg_datetime,a.call_sta_time),'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') as timestamp) 							 as SBRP_START_DT,
							cast(from_unixtime(unix_timestamp(a.EXPIRE_DATETIME,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss')  as timestamp) 						 as SBRP_STOP_DT,
							cast(NULL as INTEGER) 										 as VLDT_PERIOD_DAYS,
							cast(NULL as timestamp) 									 as LAST_RENEWED_DT,
							cast(NULL as timestamp) 									 as NEXT_RENEW_DT,
							cast(NULL as BIGINT) 							  			 as LIFE_TIME_RENEW_CNT,
							'REG_SUCCESS' 												 as SBRP_STAT_CD,
							A.REG_CODE 										 			 as SBRP_TMNT_RSN_CD,
							cast(NULL as string) 										 as CAMPAIGN_IND,
							cast(NULL as string) 										 as ROLLOVER_IND,
							a.CALLING_ISDN 												 as ORIGNTNG_NBR,
							cast(NULL as string) 										 as ORIGNTNG_IMSI,
							cast(NULL as string) 										 as ORIGNTNG_IMEI,							
							(CASE WHEN (A.LOCATION_INDICATOR = 2 OR (A.LOCATION LIKE '8491%' OR A.CELL_ID LIKE '452-02%')) 
								  THEN '1' ELSE CAST(NULL AS STRING) END) 				 AS RMNG_IND,									
							cast(NULL as string) 										 as TESTNG_NBR_IND,
							cast(NULL as string) 										 as ORIGNTNG_PLMN_CD,
							cast(NULL as string) 										 as ORIGNTNG_NETWORK_TYP,
							cast(NULL as string) 										 as ORIGNTNG_HOME_COUNTRY_CD,
							cast(NULL as string) 										 as ORIGNTNG_HOME_AREA_CD,
							cast(NULL as string) 										 as ORIGNTNG_HOME_NETWORK_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_COUNTRY_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_AREA_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_NETWORK_CD,
							cast(NULL as BIGINT) 										 as BLLG_OPRTR_KEY,
							cast(NULL as string) 										 as BLLG_OPRTR_CD,
							cast(NULL as string) 										 as BLLG_STAT_CD,
							cast(NULL as string) 										 as BLLG_STAT_RSN_CD,
							cast(NULL as string) 										 as SBRP_REQUEST_INFO,
							cast(NULL as string) 										 as SBRP_RESPONSE_INFO,
							A.CELL_ID														 										as ORIGNTNG_GCI_CD,							
							CAST(NVL(E.ADDR_LAT,C4G.ADDR_LAT) AS DECIMAL(27,8))														AS ADDR_LAT,
							CAST(NVL(E.ADDR_LON,C4G.ADDR_LON) AS DECIMAL(27,8))														AS ADDR_LON,
							NVL(E.CELL_KEY,C4G.CELL_KEY) 				 															AS CELL_KEY,
							NVL(E.CELL_CD,C4G.CELL_CD) 				 																AS CELL_CD,
							NVL(E.CELL_SITE_KEY,C4G.CELL_SITE_KEY) 		 															AS CELL_SITE_KEY,
							NVL(E.CELL_SITE_CD,C4G.CELL_SITE_CD)			 														AS CELL_SITE_CD,								
							NVL(E.NTWK_MGNT_CENTRE_KEY,C4G.NTWK_MGNT_CENTRE_KEY) 	 												AS NTWK_MGNT_CENTRE_KEY,
							NVL(E.NTWK_MGNT_CENTRE_CD,C4G.NTWK_MGNT_CENTRE_CD) 	 													AS NTWK_MGNT_CENTRE_CD,
							NVL(E.BSNS_RGN_KEY,C4G.BSNS_RGN_KEY) 			 														AS BSNS_RGN_KEY,
							NVL(E.BSNS_RGN_CD,C4G.BSNS_RGN_CD) 			 															AS BSNS_RGN_CD,
							NVL(E.BSNS_CLUSTER_KEY,C4G.BSNS_CLUSTER_KEY) 		 													AS BSNS_CLUSTER_KEY,
							NVL(E.BSNS_CLUSTER_CD,C4G.BSNS_CLUSTER_CD) 		 														AS BSNS_CLUSTER_CD,
							NVL(E.BSNS_MINICLUSTER_KEY,C4G.BSNS_MINICLUSTER_KEY) 	 												AS BSNS_MINICLUSTER_KEY,
							NVL(E.BSNS_MINICLUSTER_CD,C4G.BSNS_MINICLUSTER_CD) 	 													AS BSNS_MINICLUSTER_CD,
							NVL(E.GEO_CNTRY_KEY,C4G.GEO_CNTRY_KEY) 		 															AS GEO_CNTRY_KEY,
							NVL(E.GEO_CNTRY_CD,C4G.GEO_CNTRY_CD) 			 														AS GEO_CNTRY_CD,
							NVL(E.GEO_STATE_KEY,C4G.GEO_STATE_KEY) 		 															AS GEO_STATE_KEY,
							NVL(E.GEO_STATE_CD,C4G.GEO_STATE_CD) 			 														AS GEO_STATE_CD,
							NVL(E.GEO_DSTRCT_KEY,C4G.GEO_DSTRCT_KEY) 		 														AS GEO_DSTRCT_KEY,
							NVL(E.GEO_DSTRCT_CD,C4G.GEO_DSTRCT_CD) 		 															AS GEO_DSTRCT_CD,
							NVL(E.GEO_CITY_KEY,C4G.GEO_CITY_KEY) 			 														AS GEO_CITY_KEY,
							NVL(E.GEO_CITY_CD,C4G.GEO_CITY_CD) 			 															AS GEO_CITY_CD,	
													
							cast(b.ACQSTN_DT as timestamp) 								 as ACQSTN_DT,
							cast(b.ACQSTN_BSNS_OUTLET_KEY as BIGINT) 					 as ACQSTN_BSNS_OUTLET_KEY,
							cast(b.ACQSTN_BSNS_OUTLET_CD as string) 					 as ACQSTN_BSNS_OUTLET_CD,
							cast(NULL as INTEGER) 										 as CHRG_HEAD_KEY,
							cast(NULL as string) 										 as CHRG_HEAD_CD,
							cast(NULL as string) 										 as CHRGNG_PRTY_IND,
							cast(NULL as string) 										 as OTHR_CHRGNG_NBR,
							cast(NULL as string) 										 as CHRGING_ZONE_CD,
							cast(NULL as string) 										 as RTD_CLASS_CD,
							cast(NULL as string) 										 as RTNG_INFO,
							cast(a.credit_charged as DECIMAL(27,8)) 					 as CHRGD_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as MARK_UP_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as DISCOUNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as TAX_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as BLLD_AMT,
							cast(a.credit_charged as DECIMAL(27,8)) 					 as RVN_AMT,
							CASE WHEN c.SBRP_RC_AMT > 0 THEN cast(a.credit_charged as DECIMAL(27,8)) ELSE cast(0 as DECIMAL(27,8)) END 	 as RC_RVN_AMT,
							CASE 
								WHEN c.SBRP_NRC_AMT > 0 OR C.OFFER_KEY IS NULL THEN cast(a.credit_charged as DECIMAL(27,8)) 
								ELSE cast(0 as DECIMAL(27,8))
							END 	 as NRC_RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_TAX_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as REFUND_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_REFUND_AMT,
							cast(NULL as string) 										 as REFUND_RSN_CD,
							cast(NULL as DECIMAL(27,8)) 								 as ACTVTN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ACTVTN_BONUS_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as DEACTVTN_CHRG_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as PREPAID_MAIN_ACCT_DECRMNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as POSTPAID_MAIN_ACCT_DECRMNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as MAIN_ACCT_BAL_AMT_BEFR_IMPACT,
							cast(NULL as DECIMAL(27,8)) 								 as MAIN_ACCT_BAL_AMT_AFTR_IMPACT,
							cast(NULL as BIGINT) 								 as WALLET1_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET1_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET2_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET2_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET3_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET3_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET4_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET4_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET5_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET5_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET6_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET6_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET7_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET7_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET8_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET8_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET9_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET9_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET10_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET10_BAL_DECRMNT_AMT,
							cast(NULL as DECIMAL(12,4)) 								 as LOYALTY_RANK_SCORE,
							cast(NULL as timestamp) 									 as LOYALTY_SCORE_DT,
							cast(NULL as DECIMAL(12,4)) 								 as CREDIT_SCORE,
							cast(NULL as string) 										 as CREDIT_CLASS_CD,
							cast(NULL as string) 										 as CREDIT_SCORE_METHOD,
							cast(NULL as timestamp) 									 as CREDIT_SCORE_DT,
							cast(NULL as INTEGER) 									 as RISK_IND,
							cast(NULL as string) 										 as ACCT_SEGMENT_CD,
							cast(NULL as string) 										 as ACCT_SEGMENT_DT,
							cast(NULL as string) 										 as CMPGN_CD,
							cast(6 as BIGINT) 											 AS SRC_SYS_KEY,
							'ICC' 														 AS SRC_SYS_CD,
							CURRENT_TIMESTAMP() 										 as LOAD_DT,
							'1' 														 as CURR_IND,
							1 															 as WRHS_ID
						FROM 
						(
						select T1.TREE_ID,t1.call_type,t1.CALL_STA_TIME,t1.CALLING_ISDN,t1.TRANSACTION_DESCRIPTION,t1.CREDIT_CHARGED,t1.CELL_ID, t1.PROD_KEY, t1.PROD_CD, t1.ITEM_ID, t1.SUB_ITEM_ID, t1.LOCATION_INDICATOR,t1.LOCATION,t1.CELL_ID, vd.*, 
							ROW_NUMBER() OVER (PARTITION BY t1.CALL_STA_TIME,t1.CALLING_ISDN,t1.TRANSACTION_DESCRIPTION, t1.ftp_filename, t1.stt,t1.ITEM_ID, t1.SUB_ITEM_ID 
							ORDER BY ABS(UNIX_TIMESTAMP(vd.reg_datetime,'dd/MM/yyyy HH:mm:ss') - UNIX_TIMESTAMP(t1.CALL_STA_TIME,'dd/MM/yyyy HH:mm:ss'))) AS ROW_NUM_1
						from CDR_ICC_TMP t1 
						LEFT JOIN  mbf_datalake.vasp_dk vd 
							ON vd.day_key  = '$day_key' AND vd.isdn = t1.calling_isdn and vd.code = t1.transaction_description
						) a
						LEFT JOIN 
						(SELECT * FROM mbf_bigdata.admr_account_service WHERE day_key = '$day_key') b
							ON a.calling_isdn = b.service_nbr
						LEFT JOIN OFFER_TMP C 
							ON a.transaction_description = c.offer_cd and b.prod_line_key = c.prod_line_key and c.add_info = cast(a.program_id as string)
						LEFT JOIN MBF_BIGDATA.ADMR_CELL E 
							ON E.CELL_GCI_CD = A.CELL_ID AND E.DAY_KEY = '$day_key'
						LEFT JOIN CELL_4G_STD C4G ON A.CELL_ID = C4G.CELL_GCI_CD
						where a.ROW_NUM_1 = 1 
					",
		"tempTable" : "CDR_IN_TMP",
		"countSourceRecord" : "0"
	  },
	  {
		"sql"      : "
						SELECT 
							cast(SUBSTR('$day_key',1,6)as INTEGER) 				 as MO_KEY,
							cast(from_unixtime(unix_timestamp(a.reg_datetime,'dd/MM/yyyy HH'),'HH') as INTEGER)  	  			 as hour_key,
							cast(NULL as string) 										 as uuid,
							cast(NULL as string) 										 as SBRP_REF_CD,
							cast(from_unixtime(unix_timestamp(a.reg_datetime,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') as timestamp) 							 as SBRP_DT,
							cast(from_unixtime(unix_timestamp(a.reg_datetime,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') as timestamp) 							 as BLLG_START_DT,
							a.FTP_FILENAME 												 as FILE_NAME,
							cast(NULL as timestamp) 									 as FILE_DT,
							cast(NULL as string) 										 as FILE_PREFIX_CD,
							cast(NULL as timestamp) 									 as REC_PROCESS_DT,
							cast(NULL as string) 										 as SWITCH_CD,
							cast(b.ACCT_SRVC_INSTANCE_KEY as DECIMAL(27,0)) 			 as ACCT_SRVC_INSTANCE_KEY,
							A.ISDN 										 as SERVICE_NBR,
							cast(b.ACCT_KEY as DECIMAL(27,0)) 							 as ACCT_KEY,
							cast(b.BILLABLE_ACCT_KEY as DECIMAL(27,0)) 					 as BILLABLE_ACCT_KEY,
							cast(NULL as string) 										 as BILL_GRP_CD,
							cast(NULL as BIGINT) 										 as BILL_CYCLE_KEY,
							cast(b.CUST_KEY as DECIMAL(27,0)) 							 as CUST_KEY,
							b.CUST_TYP_CD,
							b.CORPORATE_IND,
							b.NTWK_QOS_GRP_CD,
							cast(b.ACTIVATION_DT as timestamp) 							 as ACCT_ACTIVATION_DT,
							cast(b.CBS_ACTIVATION_DT as timestamp) 						 as ACCT_CBS_ACTIVATION_DT,
							b.LFCYCL_STAT_CD 											 as ACCT_LFCYCL_STAT_CD,
							cast(b.ACTIVATION_DT as timestamp) 							 as SRVC_ACTIVATION_DT,
							cast(b.CBS_ACTIVATION_DT as timestamp) 						 as SRVC_CBS_ACTIVATION_DT,
							b.LFCYCL_STAT_CD 											 as SRVC_LFCYCL_STAT_CD,
							cast(b.PROD_LINE_KEY as INTEGER) 							 as PROD_LINE_KEY,
							cast(b.USAGE_PLAN_KEY  as BIGINT) 							 as USAGE_PLAN_KEY,
							b.USAGE_PLAN_CD 											 as USAGE_PLAN_CD,
							b.USAGE_PLAN_TYP_CD 										 as USAGE_PLAN_TYP_CD,
							cast(c.OFFER_KEY as BIGINT) 								 as OFFER_KEY,
							c.offer_cd 													 as OFFER_CD,
							c.OFFER_TYP_CD 												 as OFFER_TYP_CD,
							cast(NULL as STRING) 								 		 as PROD_KEY,
							cast(NULL as string) 										 as PROD_CD,
							CAST(NULL AS STRING)										 AS ITEM_KEY,
							CAST(NULL AS STRING)										 AS SUB_ITEM_CD,
							'SBRP' 							 							 as EVT_CLASS_CD,
							c.EVT_CTGRY_CD 												 as EVT_CTGRY_CD,
							CASE 
							WHEN c.EVT_CTGRY_CD = 'VOICE_PACK_SBRP' THEN 'VOICE_PACK_CANCEL'
							WHEN c.EVT_CTGRY_CD = 'DATA_PACK_SBRP' THEN 'DATA_PACK_CANCEL'
							WHEN c.EVT_CTGRY_CD = 'SMS_PACK_SBRP' THEN 'SMS_PACK_CANCEL'
							WHEN c.EVT_CTGRY_CD = 'BUNDLE_PACK_SBRP' THEN 'BUNDLE_PACK_CANCEL'
							ELSE 'UNKNOWN'
							END 														 as EVT_TYP_CD,
							'VND' 														 as CRNCY_CD,
							c.USAGE_TYP_CD												 as USAGE_TYP_CD,
							cast(NULL as string) 										 as SBRP_CHNL_TYP_CD,
							a.REG_CODE 									 				 as SOURCE_OF_SIGNUP_CD,
							cast(NULL as BIGINT) 										 as BSNS_OUTLET_KEY,
							cast(NULL as string) 										 as BSNS_OUTLET_CD,
							cast(NULL as string) 										 as BSNS_OUTLET_TYP_CD,
							cast(NULL as string) 										 as SALES_AGENT_ID,
							cast(from_unixtime(unix_timestamp(a.reg_datetime,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') as timestamp) 							 as SBRP_START_DT,
							cast(from_unixtime(unix_timestamp(a.end_datetime,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss')  as timestamp) 						 as SBRP_STOP_DT,
							cast(NULL as INTEGER) 										 as VLDT_PERIOD_DAYS,
							cast(NULL as timestamp) 									 as LAST_RENEWED_DT,
							cast(NULL as timestamp) 									 as NEXT_RENEW_DT,
							cast(NULL as BIGINT) 							  			 as LIFE_TIME_RENEW_CNT,
							'UNREG_SUCCESS'												 as SBRP_STAT_CD,
							A.REG_CODE 													 as SBRP_TMNT_RSN_CD,
							cast(NULL as string) 										 as CAMPAIGN_IND,
							cast(NULL as string) 										 as ROLLOVER_IND,
							a.ISDN 												 		 as ORIGNTNG_NBR,
							cast(NULL as string) 										 as ORIGNTNG_IMSI,
							cast(NULL as string) 										 as ORIGNTNG_IMEI,
							cast(NULL as string) 										 as RMNG_IND,
							cast(NULL as string) 										 as TESTNG_NBR_IND,
							cast(NULL as string) 										 as ORIGNTNG_PLMN_CD,
							cast(NULL as string) 										 as ORIGNTNG_NETWORK_TYP,
							cast(NULL as string) 										 as ORIGNTNG_HOME_COUNTRY_CD,
							cast(NULL as string) 										 as ORIGNTNG_HOME_AREA_CD,
							cast(NULL as string) 										 as ORIGNTNG_HOME_NETWORK_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_COUNTRY_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_AREA_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_NETWORK_CD,
							cast(NULL as BIGINT) 										 as BLLG_OPRTR_KEY,
							cast(NULL as string) 										 as BLLG_OPRTR_CD,
							cast(NULL as string) 										 as BLLG_STAT_CD,
							cast(NULL as string) 										 as BLLG_STAT_RSN_CD,
							cast(NULL as string) 										 as SBRP_REQUEST_INFO,
							cast(NULL as string) 										 as SBRP_RESPONSE_INFO,
							cast(NULL as string) 										 as ORIGNTNG_GCI_CD,
							cast(NULL as DECIMAL(27,8)) 								 as ADDR_LAT,
							cast(NULL as DECIMAL(27,8)) 								 as ADDR_LON,
							cast(NULL as string) 										 as CELL_KEY,
							cast(NULL as string) 										 as CELL_CD,
							cast(NULL as BIGINT) 										 as CELL_SITE_KEY,
							cast(NULL as string) 										 as CELL_SITE_CD,
							cast(NULL as BIGINT) 										 as NTWK_MGNT_CENTRE_KEY,
							cast(NULL as string) 										 as NTWK_MGNT_CENTRE_CD,
							cast(b.BSNS_RGN_KEY as BIGINT) 								 as BSNS_RGN_KEY,
							cast(b.BSNS_RGN_CD as string) 								 as BSNS_RGN_CD,
							cast(b.BSNS_CLUSTER_KEY as BIGINT) 							 as BSNS_CLUSTER_KEY,
							cast(b.BSNS_CLUSTER_CD as string) 							 as BSNS_CLUSTER_CD,
							cast(b.BSNS_MINICLUSTER_KEY as BIGINT) 						 as BSNS_MINICLUSTER_KEY,
							cast(b.BSNS_MINICLUSTER_CD as string) 						 as BSNS_MINICLUSTER_CD,
							cast(b.GEO_CNTRY_KEY as BIGINT) 							 as GEO_CNTRY_KEY,
							cast(b.GEO_CNTRY_CD as string) 								 as GEO_CNTRY_CD,
							cast(b.GEO_STATE_KEY as BIGINT) 							 as GEO_STATE_KEY,
							cast(b.GEO_STATE_CD as string) 								 as GEO_STATE_CD,
							cast(b.GEO_DSTRCT_KEY as BIGINT) 							 as GEO_DSTRCT_KEY,
							cast(b.GEO_DSTRCT_CD as string) 							 as GEO_DSTRCT_CD,
							cast(b.GEO_CITY_KEY as BIGINT) 								 as GEO_CITY_KEY,
							cast(b.GEO_CITY_CD as string) 								 as GEO_CITY_CD,
							cast(b.ACQSTN_DT as timestamp) 								 as ACQSTN_DT,
							cast(b.ACQSTN_BSNS_OUTLET_KEY as BIGINT) 					 as ACQSTN_BSNS_OUTLET_KEY,
							cast(b.ACQSTN_BSNS_OUTLET_CD as string) 					 as ACQSTN_BSNS_OUTLET_CD,
							cast(NULL as INTEGER) 										 as CHRG_HEAD_KEY,
							cast(NULL as string) 										 as CHRG_HEAD_CD,
							cast(NULL as string) 										 as CHRGNG_PRTY_IND,
							cast(NULL as string) 										 as OTHR_CHRGNG_NBR,
							cast(NULL as string) 										 as CHRGING_ZONE_CD,
							cast(NULL as string) 										 as RTD_CLASS_CD,
							cast(NULL as string) 										 as RTNG_INFO,
							cast(NULL as DECIMAL(27,8)) 					 			 as CHRGD_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as MARK_UP_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as DISCOUNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as TAX_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as BLLD_AMT,
							cast(NULL as DECIMAL(27,8)) 					 			 as RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 	 							 as RC_RVN_AMT,
							cast(NULL as DECIMAL(27,8))  	 							 as NRC_RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_TAX_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as REFUND_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_REFUND_AMT,
							cast(NULL as string) 										 as REFUND_RSN_CD,
							cast(NULL as DECIMAL(27,8)) 								 as ACTVTN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ACTVTN_BONUS_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as DEACTVTN_CHRG_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as PREPAID_MAIN_ACCT_DECRMNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as POSTPAID_MAIN_ACCT_DECRMNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as MAIN_ACCT_BAL_AMT_BEFR_IMPACT,
							cast(NULL as DECIMAL(27,8)) 								 as MAIN_ACCT_BAL_AMT_AFTR_IMPACT,
							cast(NULL as BIGINT) 								 as WALLET1_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET1_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET2_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET2_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET3_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET3_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET4_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET4_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET5_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET5_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET6_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET6_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET7_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET7_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET8_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET8_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET9_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET9_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET10_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET10_BAL_DECRMNT_AMT,
							cast(NULL as DECIMAL(12,4)) 								 as LOYALTY_RANK_SCORE,
							cast(NULL as timestamp) 									 as LOYALTY_SCORE_DT,
							cast(NULL as DECIMAL(12,4)) 								 as CREDIT_SCORE,
							cast(NULL as string) 										 as CREDIT_CLASS_CD,
							cast(NULL as string) 										 as CREDIT_SCORE_METHOD,
							cast(NULL as timestamp) 									 as CREDIT_SCORE_DT,
							cast(NULL as INTEGER) 									 	 as RISK_IND,
							cast(NULL as string) 										 as ACCT_SEGMENT_CD,
							cast(NULL as string) 										 as ACCT_SEGMENT_DT,
							cast(NULL as string) 										 as CMPGN_CD,
							cast(22 as BIGINT) 											 AS SRC_SYS_KEY,
							'VASP' 														 AS SRC_SYS_CD,
							CURRENT_TIMESTAMP() 										 as LOAD_DT,
							'1' 														 as CURR_IND,
							1 															 as WRHS_ID
						FROM 
					     MBF_DATALAKE.VASP_DEL A
						LEFT JOIN MBF_BIGDATA.ADMR_ACCOUNT_SERVICE B ON B.SERVICE_NBR = A.ISDN AND B.DAY_KEY = '$day_key'
						LEFT JOIN OFFER_TMP C ON A.CODE = C.OFFER_CD AND B.PROD_LINE_KEY  = C.PROD_LINE_KEY and c.add_info = cast(a.program_id as string)
						WHERE A.DAY_KEY = '$day_key'
					",
		"tempTable" : "VASP_DEL_TMP_1",
		"countSourceRecord" : "0"
	  },
	  {
		"sql"      : "
						SELECT 
							cast(SUBSTR('$day_key',1,6)as INTEGER) 				 as MO_KEY,
							cast(from_unixtime(unix_timestamp(vasp.reg_datetime,'dd/MM/yyyy HH'),'HH') as INTEGER)  	  			as hour_key,
							cast(NULL as string) 										 as uuid,
							cast(NULL as string) 										 as SBRP_REF_CD,
							cast(from_unixtime(unix_timestamp(vasp.end_datetime,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') as timestamp) 							 as SBRP_DT,
							cast(from_unixtime(unix_timestamp(vasp.reg_datetime,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') as timestamp) 							 as BLLG_START_DT,
							vasp.FTP_FILENAME 												 as FILE_NAME,
							cast(NULL as timestamp) 									 as FILE_DT,
							cast(NULL as string) 										 as FILE_PREFIX_CD,
							cast(NULL as timestamp) 									 as REC_PROCESS_DT,
							cast(NULL as string) 										 as SWITCH_CD,
							cast(b.ACCT_SRVC_INSTANCE_KEY as DECIMAL(27,0)) 			 as ACCT_SRVC_INSTANCE_KEY,
							VASP.ISDN													 as SERVICE_NBR,
							cast(b.ACCT_KEY as DECIMAL(27,0)) 							 as ACCT_KEY,
							cast(b.BILLABLE_ACCT_KEY as DECIMAL(27,0)) 					 as BILLABLE_ACCT_KEY,
							cast(NULL as string) 										 as BILL_GRP_CD,
							cast(NULL as BIGINT) 										 as BILL_CYCLE_KEY,
							cast(b.CUST_KEY as DECIMAL(27,0)) 							 as CUST_KEY,
							b.CUST_TYP_CD,
							b.CORPORATE_IND,
							b.NTWK_QOS_GRP_CD,
							cast(b.ACTIVATION_DT as timestamp) 							 as ACCT_ACTIVATION_DT,
							cast(b.CBS_ACTIVATION_DT as timestamp) 						 as ACCT_CBS_ACTIVATION_DT,
							b.LFCYCL_STAT_CD 											 as ACCT_LFCYCL_STAT_CD,
							cast(b.ACTIVATION_DT as timestamp) 							 as SRVC_ACTIVATION_DT,
							cast(b.CBS_ACTIVATION_DT as timestamp) 						 as SRVC_CBS_ACTIVATION_DT,
							b.LFCYCL_STAT_CD 											 as SRVC_LFCYCL_STAT_CD,
							cast(b.PROD_LINE_KEY as INTEGER) 							 as PROD_LINE_KEY,
							cast(b.USAGE_PLAN_KEY  as BIGINT) 							 as USAGE_PLAN_KEY,
							b.USAGE_PLAN_CD 											 as USAGE_PLAN_CD,
							b.USAGE_PLAN_TYP_CD 										 as USAGE_PLAN_TYP_CD,
							cast(c.OFFER_KEY as BIGINT) 								 as OFFER_KEY,
							C.OFFER_CD 													 as OFFER_CD,
							c.OFFER_TYP_CD 												 as OFFER_TYP_CD,
							cast(NULL as STRING) 								 		 as PROD_KEY,
							cast(NULL as string) 										 as PROD_CD,
							CAST(NULL AS STRING)										 AS ITEM_KEY,
							CAST(NULL AS STRING)										 AS SUB_ITEM_CD,
							'SBRP' 							 							 as EVT_CLASS_CD,
							c.EVT_CTGRY_CD 												 as EVT_CTGRY_CD,
							CASE 
								WHEN c.EVT_CTGRY_CD = 'VOICE_PACK_SBRP' THEN 'VOICE_PACK_RENEWAL'
								WHEN c.EVT_CTGRY_CD = 'DATA_PACK_SBRP'  THEN 'DATA_PACK_RENEWAL'
								WHEN c.EVT_CTGRY_CD = 'SMS_PACK_SBRP' 	THEN 'SMS_PACK_RENEWAL'
								WHEN c.EVT_CTGRY_CD = 'BUNDLE_PACK_SBRP' THEN 'BUNDLE_PACK_RENEWAL'
								ELSE 'UNKNOWN'
							END 														 as EVT_TYP_CD,
							'VND' 														 as CRNCY_CD,
							c.USAGE_TYP_CD												 as USAGE_TYP_CD,
							cast(NULL as string) 										 as SBRP_CHNL_TYP_CD,
							vasp.REG_CODE 													 as SOURCE_OF_SIGNUP_CD,
							cast(NULL as BIGINT) 										 as BSNS_OUTLET_KEY,
							cast(NULL as string) 										 as BSNS_OUTLET_CD,
							cast(NULL as string) 										 as BSNS_OUTLET_TYP_CD,
							cast(NULL as string) 										 as SALES_AGENT_ID,
							cast(from_unixtime(unix_timestamp(vasp.reg_datetime,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') as timestamp) 							 as SBRP_START_DT,
							cast(from_unixtime(unix_timestamp(vasp.end_datetime,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss')  as timestamp) 						 as SBRP_STOP_DT,
							cast(NULL as INTEGER) 										 as VLDT_PERIOD_DAYS,
							cast(NULL as timestamp) 									 as LAST_RENEWED_DT,
							cast(NULL as timestamp) 									 as NEXT_RENEW_DT,
							cast(NULL as BIGINT) 							  			 as LIFE_TIME_RENEW_CNT,
							'RENEWAL_UNSUCCESS' 										 as SBRP_STAT_CD,
							vasp.reg_code													 as SBRP_TMNT_RSN_CD,
							cast(NULL as string) 										 as CAMPAIGN_IND,
							cast(NULL as string) 										 as ROLLOVER_IND,
							vasp.ISDN 														 as ORIGNTNG_NBR,
							cast(NULL as string) 										 as ORIGNTNG_IMSI,
							cast(NULL as string) 										 as ORIGNTNG_IMEI,
							cast(NULL as string) 										 as RMNG_IND,
							cast(NULL as string) 										 as TESTNG_NBR_IND,
							cast(NULL as string) 										 as ORIGNTNG_PLMN_CD,
							cast(NULL as string) 										 as ORIGNTNG_NETWORK_TYP,
							cast(NULL as string) 										 as ORIGNTNG_HOME_COUNTRY_CD,
							cast(NULL as string) 										 as ORIGNTNG_HOME_AREA_CD,
							cast(NULL as string) 										 as ORIGNTNG_HOME_NETWORK_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_COUNTRY_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_AREA_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_NETWORK_CD,
							cast(NULL as BIGINT) 										 as BLLG_OPRTR_KEY,
							cast(NULL as string) 										 as BLLG_OPRTR_CD,
							cast(NULL as string) 										 as BLLG_STAT_CD,
							cast(NULL as string) 										 as BLLG_STAT_RSN_CD,
							cast(NULL as string) 										 as SBRP_REQUEST_INFO,
							cast(NULL as string) 										 as SBRP_RESPONSE_INFO,
							cast(NULL as string) 										 as ORIGNTNG_GCI_CD,
							cast(NULL as DECIMAL(27,8)) 								 as ADDR_LAT,
							cast(NULL as DECIMAL(27,8)) 								 as ADDR_LON,
							cast(NULL as string) 										 as CELL_KEY,
							cast(NULL as string) 										 as CELL_CD,
							cast(NULL as BIGINT) 										 as CELL_SITE_KEY,
							cast(NULL as string) 										 as CELL_SITE_CD,
							cast(NULL as BIGINT) 										 as NTWK_MGNT_CENTRE_KEY,
							cast(NULL as string) 										 as NTWK_MGNT_CENTRE_CD,
							cast(b.BSNS_RGN_KEY as BIGINT) 								 as BSNS_RGN_KEY,
							cast(b.BSNS_RGN_CD as string) 								 as BSNS_RGN_CD,
							cast(b.BSNS_CLUSTER_KEY as BIGINT) 							 as BSNS_CLUSTER_KEY,
							cast(b.BSNS_CLUSTER_CD as string) 							 as BSNS_CLUSTER_CD,
							cast(b.BSNS_MINICLUSTER_KEY as BIGINT) 						 as BSNS_MINICLUSTER_KEY,
							cast(b.BSNS_MINICLUSTER_CD as string) 						 as BSNS_MINICLUSTER_CD,
							cast(b.GEO_CNTRY_KEY as BIGINT) 							 as GEO_CNTRY_KEY,
							cast(b.GEO_CNTRY_CD as string) 								 as GEO_CNTRY_CD,
							cast(b.GEO_STATE_KEY as BIGINT) 							 as GEO_STATE_KEY,
							cast(b.GEO_STATE_CD as string) 								 as GEO_STATE_CD,
							cast(b.GEO_DSTRCT_KEY as BIGINT) 							 as GEO_DSTRCT_KEY,
							cast(b.GEO_DSTRCT_CD as string) 							 as GEO_DSTRCT_CD,
							cast(b.GEO_CITY_KEY as BIGINT) 								 as GEO_CITY_KEY,
							cast(b.GEO_CITY_CD as string) 								 as GEO_CITY_CD,
							cast(b.ACQSTN_DT as timestamp) 								 as ACQSTN_DT,
							cast(b.ACQSTN_BSNS_OUTLET_KEY as BIGINT) 					 as ACQSTN_BSNS_OUTLET_KEY,
							cast(b.ACQSTN_BSNS_OUTLET_CD as string) 					 as ACQSTN_BSNS_OUTLET_CD,
							cast(NULL as INTEGER) 										 as CHRG_HEAD_KEY,
							cast(NULL as string) 										 as CHRG_HEAD_CD,
							cast(NULL as string) 										 as CHRGNG_PRTY_IND,
							cast(NULL as string) 										 as OTHR_CHRGNG_NBR,
							cast(NULL as string) 										 as CHRGING_ZONE_CD,
							cast(NULL as string) 										 as RTD_CLASS_CD,
							cast(NULL as string) 										 as RTNG_INFO,
							cast(NULL as DECIMAL(27,8)) 					 			 as CHRGD_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as MARK_UP_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as DISCOUNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as TAX_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as BLLD_AMT,
							cast(NULL as DECIMAL(27,8)) 					 			 as RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 	 							 as RC_RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 	 							 as NRC_RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_TAX_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as REFUND_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_REFUND_AMT,
							cast(NULL as string) 										 as REFUND_RSN_CD,
							cast(NULL as DECIMAL(27,8)) 								 as ACTVTN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ACTVTN_BONUS_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as DEACTVTN_CHRG_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as PREPAID_MAIN_ACCT_DECRMNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as POSTPAID_MAIN_ACCT_DECRMNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as MAIN_ACCT_BAL_AMT_BEFR_IMPACT,
							cast(NULL as DECIMAL(27,8)) 								 as MAIN_ACCT_BAL_AMT_AFTR_IMPACT,
							cast(NULL as BIGINT) 								 		as WALLET1_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET1_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 		as WALLET2_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET2_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 		as WALLET3_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET3_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET4_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET4_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET5_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET5_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET6_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET6_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET7_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET7_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET8_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET8_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET9_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET9_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET10_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET10_BAL_DECRMNT_AMT,
							cast(NULL as DECIMAL(12,4)) 								 as LOYALTY_RANK_SCORE,
							cast(NULL as timestamp) 									 as LOYALTY_SCORE_DT,
							cast(NULL as DECIMAL(12,4)) 								 as CREDIT_SCORE,
							cast(NULL as string) 										 as CREDIT_CLASS_CD,
							cast(NULL as string) 										 as CREDIT_SCORE_METHOD,
							cast(NULL as timestamp) 									 as CREDIT_SCORE_DT,
							cast(NULL as INTEGER) 									 as RISK_IND,
							cast(NULL as string) 										 as ACCT_SEGMENT_CD,
							cast(NULL as string) 										 as ACCT_SEGMENT_DT,
							cast(NULL as string) 										 as CMPGN_CD,
							cast(22 as BIGINT) 											 AS SRC_SYS_KEY,
							'VASP' 														 AS SRC_SYS_CD,
							CURRENT_TIMESTAMP() 										 as LOAD_DT,
							'1' 														 as CURR_IND,
							1 															 as WRHS_ID
						FROM 
						  (
						SELECT         
							   A.*
						FROM MBF_DATALAKE.VASP_DEL A
						WHERE A.DAY_KEY = '$day_key'  AND A.REG_CODE = 'VASP' AND FROM_UNIXTIME(UNIX_TIMESTAMP(A.END_DATETIME,'dd/MM/yyyy HH:mm:ss'),'yyyyMMdd') = '$day_key'
						AND not exists
								(SELECT 1
								FROM mbf_datalake.vasp_dk b
								WHERE day_key = '$day_key'
								AND reg_code = 'VASP' and 
								FROM_UNIXTIME(UNIX_TIMESTAMP(B.REG_DATETIME,'dd/MM/yyyy HH:mm:ss'),'yyyyMMdd') = '$day_key'   
								and a.profile = b.profile and a.code = b.code and a.group_code = b.group_code and a.isdn = b.isdn) ) VASP
						LEFT JOIN MBF_BIGDATA.ADMR_ACCOUNT_SERVICE B ON B.SERVICE_NBR=VASP.ISDN AND B.DAY_KEY = '$day_key'
						LEFT JOIN OFFER_TMP C ON c.OFFER_CD= VASP.CODE and B.PROD_LINE_KEY = c.PROD_LINE_KEY and c.add_info = cast(VASP.program_id as string)
					",
		"tempTable" : "VASP_DEL_TMP_2",
		"countSourceRecord" : "0"
	  },
	  {
		"sql"      : "
						SELECT 
							cast(SUBSTR('$day_key',1,6)as INTEGER) 			 as MO_KEY,
							cast(from_unixtime(unix_timestamp(vasp.reg_date,'dd/MM/yyyy HH'),'HH') as INTEGER)  	  			as hour_key,
							cast(NULL as string) 										 as uuid,
							cast(NULL as string) 										 as SBRP_REF_CD,
							cast(from_unixtime(unix_timestamp(vasp.LAST_RETRY_DATE,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') as timestamp) 							 as SBRP_DT,
							cast(from_unixtime(unix_timestamp(vasp.reg_date,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') as timestamp) 							 as BLLG_START_DT,
							vasp.FTP_FILENAME 												 as FILE_NAME,
							cast(NULL as timestamp) 									 as FILE_DT,
							cast(NULL as string) 										 as FILE_PREFIX_CD,
							cast(NULL as timestamp) 									 as REC_PROCESS_DT,
							cast(NULL as string) 										 as SWITCH_CD,
							cast(b.ACCT_SRVC_INSTANCE_KEY as DECIMAL(27,0)) 			 as ACCT_SRVC_INSTANCE_KEY,
							VASP.ISDN 										 as SERVICE_NBR,
							cast(b.ACCT_KEY as DECIMAL(27,0)) 							 as ACCT_KEY,
							cast(b.BILLABLE_ACCT_KEY as DECIMAL(27,0)) 					 as BILLABLE_ACCT_KEY,
							cast(NULL as string) 										 as BILL_GRP_CD,
							cast(NULL as BIGINT) 										 as BILL_CYCLE_KEY,
							cast(b.CUST_KEY as DECIMAL(27,0)) 							 as CUST_KEY,
							b.CUST_TYP_CD,
							b.CORPORATE_IND,
							b.NTWK_QOS_GRP_CD,
							cast(b.ACTIVATION_DT as timestamp) 							 as ACCT_ACTIVATION_DT,
							cast(b.CBS_ACTIVATION_DT as timestamp) 						 as ACCT_CBS_ACTIVATION_DT,
							b.LFCYCL_STAT_CD 											 as ACCT_LFCYCL_STAT_CD,
							cast(b.ACTIVATION_DT as timestamp) 							 as SRVC_ACTIVATION_DT,
							cast(b.CBS_ACTIVATION_DT as timestamp) 						 as SRVC_CBS_ACTIVATION_DT,
							b.LFCYCL_STAT_CD 											 as SRVC_LFCYCL_STAT_CD,
							cast(b.PROD_LINE_KEY as INTEGER) 							 as PROD_LINE_KEY,
							cast(b.USAGE_PLAN_KEY  as BIGINT) 							 as USAGE_PLAN_KEY,
							b.USAGE_PLAN_CD 											 as USAGE_PLAN_CD,
							b.USAGE_PLAN_TYP_CD 										 as USAGE_PLAN_TYP_CD,
							cast(c.OFFER_KEY as BIGINT) 								 as OFFER_KEY,
							C.OFFER_CD 													 as OFFER_CD,
							c.OFFER_TYP_CD 												 as OFFER_TYP_CD,
							cast(NULL as STRING) 										 as PROD_KEY,
							cast(NULL as string) 										 as PROD_CD,
							CAST(NULL AS STRING)										 AS ITEM_KEY,
							CAST(NULL AS STRING)										 AS SUB_ITEM_CD,
							'SBRP' 							 							 as EVT_CLASS_CD,
							c.EVT_CTGRY_CD 												 as EVT_CTGRY_CD,
							CASE 
								WHEN c.EVT_CTGRY_CD = 'VOICE_PACK_SBRP' THEN 'VOICE_PACK_RENEWAL'
								WHEN c.EVT_CTGRY_CD = 'DATA_PACK_SBRP'  THEN 'DATA_PACK_RENEWAL'
								WHEN c.EVT_CTGRY_CD = 'SMS_PACK_SBRP' 	THEN 'SMS_PACK_RENEWAL'
								WHEN c.EVT_CTGRY_CD = 'BUNDLE_PACK_SBRP' THEN 'BUNDLE_PACK_RENEWAL'
								ELSE 'UNKNOWN'
							END 														 as EVT_TYP_CD,
							'VND' 														 as CRNCY_CD,
							c.USAGE_TYP_CD												 as USAGE_TYP_CD,
							cast(NULL as string) 										 as SBRP_CHNL_TYP_CD,
							cast(NULL as string) 										 as SOURCE_OF_SIGNUP_CD,
							cast(NULL as BIGINT) 										 as BSNS_OUTLET_KEY,
							cast(NULL as string) 										 as BSNS_OUTLET_CD,
							cast(NULL as string) 										 as BSNS_OUTLET_TYP_CD,
							cast(NULL as string) 										 as SALES_AGENT_ID,
							cast(from_unixtime(unix_timestamp(vasp.reg_date,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') as timestamp) 						as SBRP_START_DT,
							cast(from_unixtime(unix_timestamp(vasp.end_date,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss')  as timestamp) 						 as SBRP_STOP_DT,
							cast(NULL as INTEGER) 										 as VLDT_PERIOD_DAYS,
							cast(NULL as timestamp) 									 as LAST_RENEWED_DT,
							cast(NULL as timestamp) 									 as NEXT_RENEW_DT,
							cast(NULL as BIGINT) 							  			 as LIFE_TIME_RENEW_CNT,
							CASE 
								WHEN VASP.LAST_RESPONSE_MSG LIKE '%SUCC%'
									 OR VASP.LAST_RESPONSE_MSG LIKE '%RETRY_GH_30DAY_SUCC%'
									 OR VASP.LAST_RESPONSE_MSG LIKE '%DK_GH_APPEND%'
								  THEN 'RETRY_SUCCESS' 
								WHEN VASP.RETRY_STATUS = '1'
									 AND VASP.LAST_RESPONSE_MSG NOT LIKE '%SUCC%'
									 AND VASP.LAST_RESPONSE_MSG NOT LIKE '%RETRY_GH_30DAY_SUCC%'
									 AND VASP.LAST_RESPONSE_MSG NOT LIKE '%DK_GH_APPEND%'
									 AND CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(VASP.end_date,'dd/MM/yyyy HH:mm:ss')) AS TIMESTAMP) >= DATE_ADD(FROM_UNIXTIME(UNIX_TIMESTAMP('$day_key','yyyyMMdd')),-30)
								  THEN 'RETRY_UNSUCCESS'
								WHEN CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(VASP.end_date,'dd/MM/yyyy HH:mm:ss')) AS TIMESTAMP) < DATE_ADD(FROM_UNIXTIME(UNIX_TIMESTAMP('$day_key','yyyyMMdd')),-30)
								  THEN 'RETRY_UNSUCCESS_EXPIRE'
								ELSE 'RETRY_UNKNOWN'
							END										 					 as SBRP_STAT_CD,
							CAST(NULL AS STRING)										 as SBRP_TMNT_RSN_CD,
							cast(NULL as string) 										 as CAMPAIGN_IND,
							cast(NULL as string) 										 as ROLLOVER_IND,
							vasp.ISDN 													 as ORIGNTNG_NBR,
							cast(NULL as string) 										 as ORIGNTNG_IMSI,
							cast(NULL as string) 										 as ORIGNTNG_IMEI,
							cast(NULL as string) 										 as RMNG_IND,
							cast(NULL as string) 										 as TESTNG_NBR_IND,
							cast(NULL as string) 										 as ORIGNTNG_PLMN_CD,
							cast(NULL as string) 										 as ORIGNTNG_NETWORK_TYP,
							cast(NULL as string) 										 as ORIGNTNG_HOME_COUNTRY_CD,
							cast(NULL as string) 										 as ORIGNTNG_HOME_AREA_CD,
							cast(NULL as string) 										 as ORIGNTNG_HOME_NETWORK_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_COUNTRY_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_AREA_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_NETWORK_CD,
							cast(NULL as BIGINT) 										 as BLLG_OPRTR_KEY,
							cast(NULL as string) 										 as BLLG_OPRTR_CD,
							cast(NULL as string) 										 as BLLG_STAT_CD,
							cast(NULL as string) 										 as BLLG_STAT_RSN_CD,
							cast(NULL as string) 										 as SBRP_REQUEST_INFO,
							cast(NULL as string) 										 as SBRP_RESPONSE_INFO,
							cast(NULL as string) 										 as ORIGNTNG_GCI_CD,
							cast(NULL as DECIMAL(27,8)) 								 as ADDR_LAT,
							cast(NULL as DECIMAL(27,8)) 								 as ADDR_LON,
							cast(NULL as string) 										 as CELL_KEY,
							cast(NULL as string) 										 as CELL_CD,
							cast(NULL as BIGINT) 										 as CELL_SITE_KEY,
							cast(NULL as string) 										 as CELL_SITE_CD,
							cast(NULL as BIGINT) 										 as NTWK_MGNT_CENTRE_KEY,
							cast(NULL as string) 										 as NTWK_MGNT_CENTRE_CD,
							cast(b.BSNS_RGN_KEY as BIGINT) 								 as BSNS_RGN_KEY,
							cast(b.BSNS_RGN_CD as string) 								 as BSNS_RGN_CD,
							cast(b.BSNS_CLUSTER_KEY as BIGINT) 							 as BSNS_CLUSTER_KEY,
							cast(b.BSNS_CLUSTER_CD as string) 							 as BSNS_CLUSTER_CD,
							cast(b.BSNS_MINICLUSTER_KEY as BIGINT) 						 as BSNS_MINICLUSTER_KEY,
							cast(b.BSNS_MINICLUSTER_CD as string) 						 as BSNS_MINICLUSTER_CD,
							cast(b.GEO_CNTRY_KEY as BIGINT) 							 as GEO_CNTRY_KEY,
							cast(b.GEO_CNTRY_CD as string) 								 as GEO_CNTRY_CD,
							cast(b.GEO_STATE_KEY as BIGINT) 							 as GEO_STATE_KEY,
							cast(b.GEO_STATE_CD as string) 								 as GEO_STATE_CD,
							cast(b.GEO_DSTRCT_KEY as BIGINT) 							 as GEO_DSTRCT_KEY,
							cast(b.GEO_DSTRCT_CD as string) 							 as GEO_DSTRCT_CD,
							cast(b.GEO_CITY_KEY as BIGINT) 								 as GEO_CITY_KEY,
							cast(b.GEO_CITY_CD as string) 								 as GEO_CITY_CD,
							cast(b.ACQSTN_DT as timestamp) 								 as ACQSTN_DT,
							cast(b.ACQSTN_BSNS_OUTLET_KEY as BIGINT) 					 as ACQSTN_BSNS_OUTLET_KEY,
							cast(b.ACQSTN_BSNS_OUTLET_CD as string) 					 as ACQSTN_BSNS_OUTLET_CD,
							cast(NULL as INTEGER) 										 as CHRG_HEAD_KEY,
							cast(NULL as string) 										 as CHRG_HEAD_CD,
							cast(NULL as string) 										 as CHRGNG_PRTY_IND,
							cast(NULL as string) 										 as OTHR_CHRGNG_NBR,
							cast(NULL as string) 										 as CHRGING_ZONE_CD,
							cast(NULL as string) 										 as RTD_CLASS_CD,
							cast(NULL as string) 										 as RTNG_INFO,
							cast(NULL as DECIMAL(27,8)) 					 			 as CHRGD_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as MARK_UP_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as DISCOUNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as TAX_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as BLLD_AMT,
							cast(NULL as DECIMAL(27,8)) 					 			 as RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 	 							 as RC_RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 	 							 as NRC_RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_TAX_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as REFUND_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_REFUND_AMT,
							cast(NULL as string) 										 as REFUND_RSN_CD,
							cast(NULL as DECIMAL(27,8)) 								 as ACTVTN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ACTVTN_BONUS_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as DEACTVTN_CHRG_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as PREPAID_MAIN_ACCT_DECRMNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as POSTPAID_MAIN_ACCT_DECRMNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as MAIN_ACCT_BAL_AMT_BEFR_IMPACT,
							cast(NULL as DECIMAL(27,8)) 								 as MAIN_ACCT_BAL_AMT_AFTR_IMPACT,
							cast(NULL as BIGINT) 								 		as WALLET1_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET1_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 		as WALLET2_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET2_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 		as WALLET3_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET3_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET4_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET4_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET5_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET5_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET6_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET6_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET7_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET7_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET8_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET8_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET9_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET9_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET10_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET10_BAL_DECRMNT_AMT,
							cast(NULL as DECIMAL(12,4)) 								 as LOYALTY_RANK_SCORE,
							cast(NULL as timestamp) 									 as LOYALTY_SCORE_DT,
							cast(NULL as DECIMAL(12,4)) 								 as CREDIT_SCORE,
							cast(NULL as string) 										 as CREDIT_CLASS_CD,
							cast(NULL as string) 										 as CREDIT_SCORE_METHOD,
							cast(NULL as timestamp) 									 as CREDIT_SCORE_DT,
							cast(NULL as INTEGER) 									 as RISK_IND,
							cast(NULL as string) 										 as ACCT_SEGMENT_CD,
							cast(NULL as string) 										 as ACCT_SEGMENT_DT,
							cast(NULL as string) 										 as CMPGN_CD,
							cast(22 as BIGINT) 											 AS SRC_SYS_KEY,
							'VASP' 														 AS SRC_SYS_CD,
							CURRENT_TIMESTAMP() 										 as LOAD_DT,
							'1' 														 as CURR_IND,
							1 															 as WRHS_ID
						FROM 
							(SELECT VR.*, VA.PROGRAM_ID
							FROM MBF_DATALAKE.VASP_RETRY VR
							LEFT JOIN MBF_DATALAKE.VASP_ACTIVE VA
								ON VR.ISDN = VA.ISDN 
								AND VR.CODE = VA.CODE
								AND VR.DAY_KEY = VA.DAY_KEY
							WHERE VR.DAY_KEY = '$day_key' AND VA.PROGRAM_ID IS NOT NULL) VASP
						LEFT JOIN MBF_BIGDATA.ADMR_ACCOUNT_SERVICE B ON B.SERVICE_NBR= VASP.ISDN AND B.DAY_KEY = '$day_key'
						LEFT JOIN OFFER_TMP C ON c.OFFER_CD= VASP.CODE and B.PROD_LINE_KEY = c.PROD_LINE_KEY AND c.add_info = cast(VASP.program_id as string)
						WHERE VASP.DAY_KEY = '$day_key' AND FROM_UNIXTIME(UNIX_TIMESTAMP(VASP.END_DATE,'dd/MM/yyyy HH:mm:ss'),'yyyyMMdd') = '$day_key'
						
					",
		"tempTable" : "VASP_RETRY_TMP_1",
		"countSourceRecord" : "0"
	  },
	  {
		"sql"      : "
						SELECT 
							cast(SUBSTR('$day_key',1,6)as INTEGER) 				 as MO_KEY,
							cast(from_unixtime(unix_timestamp(vasp.reg_date,'dd/MM/yyyy HH'),'HH') as INTEGER)  	  			as hour_key,
							cast(NULL as string) 										 as uuid,
							cast(NULL as string) 										 as SBRP_REF_CD,
							cast(from_unixtime(unix_timestamp(vasp.LAST_RETRY_DATE,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') as timestamp) 							 as SBRP_DT,
							cast(from_unixtime(unix_timestamp(vasp.reg_date,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') as timestamp) 							 as BLLG_START_DT,
							vasp.FTP_FILENAME 												 as FILE_NAME,
							cast(NULL as timestamp) 									 as FILE_DT,
							cast(NULL as string) 										 as FILE_PREFIX_CD,
							cast(NULL as timestamp) 									 as REC_PROCESS_DT,
							cast(NULL as string) 										 as SWITCH_CD,
							cast(b.ACCT_SRVC_INSTANCE_KEY as DECIMAL(27,0)) 			 as ACCT_SRVC_INSTANCE_KEY,
							VASP.ISDN 										 as SERVICE_NBR,
							cast(b.ACCT_KEY as DECIMAL(27,0)) 							 as ACCT_KEY,
							cast(b.BILLABLE_ACCT_KEY as DECIMAL(27,0)) 					 as BILLABLE_ACCT_KEY,
							cast(NULL as string) 										 as BILL_GRP_CD,
							cast(NULL as BIGINT) 										 as BILL_CYCLE_KEY,
							cast(b.CUST_KEY as DECIMAL(27,0)) 							 as CUST_KEY,
							b.CUST_TYP_CD,
							b.CORPORATE_IND,
							b.NTWK_QOS_GRP_CD,
							cast(b.ACTIVATION_DT as timestamp) 							 as ACCT_ACTIVATION_DT,
							cast(b.CBS_ACTIVATION_DT as timestamp) 						 as ACCT_CBS_ACTIVATION_DT,
							b.LFCYCL_STAT_CD 											 as ACCT_LFCYCL_STAT_CD,
							cast(b.ACTIVATION_DT as timestamp) 							 as SRVC_ACTIVATION_DT,
							cast(b.CBS_ACTIVATION_DT as timestamp) 						 as SRVC_CBS_ACTIVATION_DT,
							b.LFCYCL_STAT_CD 											 as SRVC_LFCYCL_STAT_CD,
							cast(b.PROD_LINE_KEY as INTEGER) 							 as PROD_LINE_KEY,
							cast(b.USAGE_PLAN_KEY  as BIGINT) 							 as USAGE_PLAN_KEY,
							b.USAGE_PLAN_CD 											 as USAGE_PLAN_CD,
							b.USAGE_PLAN_TYP_CD 										 as USAGE_PLAN_TYP_CD,
							cast(c.OFFER_KEY as BIGINT) 								 as OFFER_KEY,
							C.OFFER_CD 													 as OFFER_CD,
							c.OFFER_TYP_CD 												 as OFFER_TYP_CD,
							cast(NULL as STRING) 										 as PROD_KEY,
							cast(NULL as string) 										 as PROD_CD,
							CAST(NULL AS STRING)										 AS ITEM_KEY,
							CAST(NULL AS STRING)										 AS SUB_ITEM_CD,
							'SBRP' 							 							 as EVT_CLASS_CD,
							c.EVT_CTGRY_CD 												 as EVT_CTGRY_CD,
							CASE 
								WHEN c.EVT_CTGRY_CD = 'VOICE_PACK_SBRP' THEN 'VOICE_PACK_RENEWAL'
								WHEN c.EVT_CTGRY_CD = 'DATA_PACK_SBRP'  THEN 'DATA_PACK_RENEWAL'
								WHEN c.EVT_CTGRY_CD = 'SMS_PACK_SBRP' 	THEN 'SMS_PACK_RENEWAL'
								WHEN c.EVT_CTGRY_CD = 'BUNDLE_PACK_SBRP' THEN 'BUNDLE_PACK_RENEWAL'
								ELSE 'UNKNOWN'
							END 														 as EVT_TYP_CD,
							'VND' 														 as CRNCY_CD,
							c.USAGE_TYP_CD												 as USAGE_TYP_CD,
							cast(NULL as string) 										 as SBRP_CHNL_TYP_CD,
							cast(NULL as string) 										 as SOURCE_OF_SIGNUP_CD,
							cast(NULL as BIGINT) 										 as BSNS_OUTLET_KEY,
							cast(NULL as string) 										 as BSNS_OUTLET_CD,
							cast(NULL as string) 										 as BSNS_OUTLET_TYP_CD,
							cast(NULL as string) 										 as SALES_AGENT_ID,
							cast(from_unixtime(unix_timestamp(vasp.reg_date,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') as timestamp) 						as SBRP_START_DT,
							cast(from_unixtime(unix_timestamp(vasp.end_date,'dd/MM/yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss')  as timestamp) 						 as SBRP_STOP_DT,
							cast(NULL as INTEGER) 										 as VLDT_PERIOD_DAYS,
							cast(NULL as timestamp) 									 as LAST_RENEWED_DT,
							cast(NULL as timestamp) 									 as NEXT_RENEW_DT,
							cast(NULL as BIGINT) 							  			 as LIFE_TIME_RENEW_CNT,
							CASE 
								WHEN VASP.LAST_RESPONSE_MSG LIKE '%SUCC%'
									 OR VASP.LAST_RESPONSE_MSG LIKE '%RETRY_GH_30DAY_SUCC%'
									 OR VASP.LAST_RESPONSE_MSG LIKE '%DK_GH_APPEND%'
								  THEN 'RETRY_SUCCESS' 
								WHEN VASP.RETRY_STATUS = '1'
									 AND VASP.LAST_RESPONSE_MSG NOT LIKE '%SUCC%'
									 AND VASP.LAST_RESPONSE_MSG NOT LIKE '%RETRY_GH_30DAY_SUCC%'
									 AND VASP.LAST_RESPONSE_MSG NOT LIKE '%DK_GH_APPEND%'
									 AND CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(VASP.end_date,'dd/MM/yyyy HH:mm:ss')) AS TIMESTAMP) >= DATE_ADD(FROM_UNIXTIME(UNIX_TIMESTAMP('$day_key','yyyyMMdd')),-30)
								  THEN 'RETRY_UNSUCCESS'
								WHEN CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(VASP.end_date,'dd/MM/yyyy HH:mm:ss')) AS TIMESTAMP) < DATE_ADD(FROM_UNIXTIME(UNIX_TIMESTAMP('$day_key','yyyyMMdd')),-30)
								  THEN 'RETRY_UNSUCCESS_EXPIRE'
								ELSE 'RETRY_UNKNOWN'
							END										 					 as SBRP_STAT_CD,
							CAST(NULL AS STRING)										 as SBRP_TMNT_RSN_CD,
							cast(NULL as string) 										 as CAMPAIGN_IND,
							cast(NULL as string) 										 as ROLLOVER_IND,
							vasp.ISDN 													 as ORIGNTNG_NBR,
							cast(NULL as string) 										 as ORIGNTNG_IMSI,
							cast(NULL as string) 										 as ORIGNTNG_IMEI,
							cast(NULL as string) 										 as RMNG_IND,
							cast(NULL as string) 										 as TESTNG_NBR_IND,
							cast(NULL as string) 										 as ORIGNTNG_PLMN_CD,
							cast(NULL as string) 										 as ORIGNTNG_NETWORK_TYP,
							cast(NULL as string) 										 as ORIGNTNG_HOME_COUNTRY_CD,
							cast(NULL as string) 										 as ORIGNTNG_HOME_AREA_CD,
							cast(NULL as string) 										 as ORIGNTNG_HOME_NETWORK_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_COUNTRY_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_AREA_CD,
							cast(NULL as string) 										 as ORIGNTNG_ROAM_NETWORK_CD,
							cast(NULL as BIGINT) 										 as BLLG_OPRTR_KEY,
							cast(NULL as string) 										 as BLLG_OPRTR_CD,
							cast(NULL as string) 										 as BLLG_STAT_CD,
							cast(NULL as string) 										 as BLLG_STAT_RSN_CD,
							cast(NULL as string) 										 as SBRP_REQUEST_INFO,
							cast(NULL as string) 										 as SBRP_RESPONSE_INFO,
							cast(NULL as string) 										 as ORIGNTNG_GCI_CD,
							cast(NULL as DECIMAL(27,8)) 								 as ADDR_LAT,
							cast(NULL as DECIMAL(27,8)) 								 as ADDR_LON,
							cast(NULL as string) 										 as CELL_KEY,
							cast(NULL as string) 										 as CELL_CD,
							cast(NULL as BIGINT) 										 as CELL_SITE_KEY,
							cast(NULL as string) 										 as CELL_SITE_CD,
							cast(NULL as BIGINT) 										 as NTWK_MGNT_CENTRE_KEY,
							cast(NULL as string) 										 as NTWK_MGNT_CENTRE_CD,
							cast(b.BSNS_RGN_KEY as BIGINT) 								 as BSNS_RGN_KEY,
							cast(b.BSNS_RGN_CD as string) 								 as BSNS_RGN_CD,
							cast(b.BSNS_CLUSTER_KEY as BIGINT) 							 as BSNS_CLUSTER_KEY,
							cast(b.BSNS_CLUSTER_CD as string) 							 as BSNS_CLUSTER_CD,
							cast(b.BSNS_MINICLUSTER_KEY as BIGINT) 						 as BSNS_MINICLUSTER_KEY,
							cast(b.BSNS_MINICLUSTER_CD as string) 						 as BSNS_MINICLUSTER_CD,
							cast(b.GEO_CNTRY_KEY as BIGINT) 							 as GEO_CNTRY_KEY,
							cast(b.GEO_CNTRY_CD as string) 								 as GEO_CNTRY_CD,
							cast(b.GEO_STATE_KEY as BIGINT) 							 as GEO_STATE_KEY,
							cast(b.GEO_STATE_CD as string) 								 as GEO_STATE_CD,
							cast(b.GEO_DSTRCT_KEY as BIGINT) 							 as GEO_DSTRCT_KEY,
							cast(b.GEO_DSTRCT_CD as string) 							 as GEO_DSTRCT_CD,
							cast(b.GEO_CITY_KEY as BIGINT) 								 as GEO_CITY_KEY,
							cast(b.GEO_CITY_CD as string) 								 as GEO_CITY_CD,
							cast(b.ACQSTN_DT as timestamp) 								 as ACQSTN_DT,
							cast(b.ACQSTN_BSNS_OUTLET_KEY as BIGINT) 					 as ACQSTN_BSNS_OUTLET_KEY,
							cast(b.ACQSTN_BSNS_OUTLET_CD as string) 					 as ACQSTN_BSNS_OUTLET_CD,
							cast(NULL as INTEGER) 										 as CHRG_HEAD_KEY,
							cast(NULL as string) 										 as CHRG_HEAD_CD,
							cast(NULL as string) 										 as CHRGNG_PRTY_IND,
							cast(NULL as string) 										 as OTHR_CHRGNG_NBR,
							cast(NULL as string) 										 as CHRGING_ZONE_CD,
							cast(NULL as string) 										 as RTD_CLASS_CD,
							cast(NULL as string) 										 as RTNG_INFO,
							cast(NULL as DECIMAL(27,8)) 					 			 as CHRGD_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as MARK_UP_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as DISCOUNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as TAX_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as BLLD_AMT,
							cast(NULL as DECIMAL(27,8)) 					 			 as RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 	 							 as RC_RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 	 							 as NRC_RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_RVN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_TAX_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as REFUND_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ECB_REFUND_AMT,
							cast(NULL as string) 										 as REFUND_RSN_CD,
							cast(NULL as DECIMAL(27,8)) 								 as ACTVTN_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as ACTVTN_BONUS_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as DEACTVTN_CHRG_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as PREPAID_MAIN_ACCT_DECRMNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as POSTPAID_MAIN_ACCT_DECRMNT_AMT,
							cast(NULL as DECIMAL(27,8)) 								 as MAIN_ACCT_BAL_AMT_BEFR_IMPACT,
							cast(NULL as DECIMAL(27,8)) 								 as MAIN_ACCT_BAL_AMT_AFTR_IMPACT,
							cast(NULL as BIGINT) 								 		as WALLET1_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET1_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 		as WALLET2_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET2_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 		as WALLET3_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET3_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET4_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET4_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET5_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET5_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET6_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET6_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET7_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET7_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET8_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET8_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET9_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET9_BAL_DECRMNT_AMT,
							cast(NULL as BIGINT) 								 as WALLET10_KEY,
							cast(NULL as DECIMAL(27,8)) 								 as WALLET10_BAL_DECRMNT_AMT,
							cast(NULL as DECIMAL(12,4)) 								 as LOYALTY_RANK_SCORE,
							cast(NULL as timestamp) 									 as LOYALTY_SCORE_DT,
							cast(NULL as DECIMAL(12,4)) 								 as CREDIT_SCORE,
							cast(NULL as string) 										 as CREDIT_CLASS_CD,
							cast(NULL as string) 										 as CREDIT_SCORE_METHOD,
							cast(NULL as timestamp) 									 as CREDIT_SCORE_DT,
							cast(NULL as INTEGER) 									 as RISK_IND,
							cast(NULL as string) 										 as ACCT_SEGMENT_CD,
							cast(NULL as string) 										 as ACCT_SEGMENT_DT,
							cast(NULL as string) 										 as CMPGN_CD,
							cast(22 as BIGINT) 											 AS SRC_SYS_KEY,
							'VASP' 														 AS SRC_SYS_CD,
							CURRENT_TIMESTAMP() 										 as LOAD_DT,
							'1' 														 as CURR_IND,
							1 															 as WRHS_ID
						FROM 
							(SELECT VR.*
							FROM MBF_DATALAKE.VASP_RETRY VR
							LEFT JOIN MBF_DATALAKE.VASP_ACTIVE VA
								ON VR.ISDN = VA.ISDN 
								AND VR.CODE = VA.CODE
								AND VR.DAY_KEY = VA.DAY_KEY
							WHERE VR.DAY_KEY = '$day_key' AND VA.PROGRAM_ID IS NULL) VASP
						LEFT JOIN MBF_BIGDATA.ADMR_ACCOUNT_SERVICE B ON B.SERVICE_NBR= VASP.ISDN AND B.DAY_KEY = '$day_key'
						LEFT JOIN OFFER_TMP_ROWNUMBER C ON c.OFFER_CD= VASP.CODE and B.PROD_LINE_KEY = c.PROD_LINE_KEY
						WHERE VASP.DAY_KEY = '$day_key' AND FROM_UNIXTIME(UNIX_TIMESTAMP(VASP.END_DATE,'dd/MM/yyyy HH:mm:ss'),'yyyyMMdd') = '$day_key'
						
					",
		"tempTable" : "VASP_RETRY_TMP_2",
		"countSourceRecord" : "0"
	  },
	  {
		"sql"      : "
						SELECT 
							MO_KEY	,
							HOUR_KEY	,
							UUID	,
							SBRP_REF_CD	,
							SBRP_DT	,
							BLLG_START_DT	,
							FILE_NAME	,
							FILE_DT	,
							FILE_PREFIX_CD	,
							REC_PROCESS_DT	,
							SWITCH_CD	,
							ACCT_SRVC_INSTANCE_KEY	,
							SERVICE_NBR	,
							ACCT_KEY	,
							BILLABLE_ACCT_KEY	,
							BILL_GRP_CD	,
							BILL_CYCLE_KEY	,
							CUST_KEY	,
							CUST_TYP_CD	,
							CORPORATE_IND	,
							NTWK_QOS_GRP_CD	,
							ACCT_ACTIVATION_DT	,
							ACCT_CBS_ACTIVATION_DT	,
							ACCT_LFCYCL_STAT_CD	,
							SRVC_ACTIVATION_DT	,
							SRVC_CBS_ACTIVATION_DT	,
							SRVC_LFCYCL_STAT_CD	,
							PROD_LINE_KEY	,
							USAGE_PLAN_KEY	,
							USAGE_PLAN_CD	,
							USAGE_PLAN_TYP_CD	,
							OFFER_KEY	,
							OFFER_CD	,
							OFFER_TYP_CD	,
							PROD_KEY	,
							PROD_CD	,
							ITEM_KEY,
							SUB_ITEM_CD,
							EVT_CLASS_CD	,
							EVT_CTGRY_CD	,
							EVT_TYP_CD	,
							CRNCY_CD	,
							USAGE_TYP_CD	,
							SBRP_CHNL_TYP_CD	,
							SOURCE_OF_SIGNUP_CD	,
							BSNS_OUTLET_KEY	,
							BSNS_OUTLET_CD	,
							BSNS_OUTLET_TYP_CD	,
							SALES_AGENT_ID	,
							SBRP_START_DT	,
							SBRP_STOP_DT	,
							VLDT_PERIOD_DAYS	,
							LAST_RENEWED_DT	,
							NEXT_RENEW_DT	,
							LIFE_TIME_RENEW_CNT	,
							SBRP_STAT_CD	,
							SBRP_TMNT_RSN_CD	,
							CAMPAIGN_IND	,
							ROLLOVER_IND	,
							ORIGNTNG_NBR	,
							ORIGNTNG_IMSI	,
							ORIGNTNG_IMEI	,
							RMNG_IND	,
							TESTNG_NBR_IND	,
							ORIGNTNG_PLMN_CD	,
							ORIGNTNG_NETWORK_TYP	,
							ORIGNTNG_HOME_COUNTRY_CD	,
							ORIGNTNG_HOME_AREA_CD	,
							ORIGNTNG_HOME_NETWORK_CD	,
							ORIGNTNG_ROAM_COUNTRY_CD	,
							ORIGNTNG_ROAM_AREA_CD	,
							ORIGNTNG_ROAM_NETWORK_CD	,
							BLLG_OPRTR_KEY	,
							BLLG_OPRTR_CD	,
							BLLG_STAT_CD	,
							BLLG_STAT_RSN_CD	,
							SBRP_REQUEST_INFO	,
							SBRP_RESPONSE_INFO	,
							ORIGNTNG_GCI_CD	,
							ADDR_LAT	,
							ADDR_LON	,
							CELL_KEY	,
							CELL_CD	,
							CELL_SITE_KEY	,
							CELL_SITE_CD	,
							NTWK_MGNT_CENTRE_KEY	,
							NTWK_MGNT_CENTRE_CD	,
							BSNS_RGN_KEY	,
							BSNS_RGN_CD	,
							BSNS_CLUSTER_KEY	,
							BSNS_CLUSTER_CD	,
							BSNS_MINICLUSTER_KEY	,
							BSNS_MINICLUSTER_CD	,
							GEO_CNTRY_KEY	,
							GEO_CNTRY_CD	,
							GEO_STATE_KEY	,
							GEO_STATE_CD	,
							GEO_DSTRCT_KEY	,
							GEO_DSTRCT_CD	,
							GEO_CITY_KEY	,
							GEO_CITY_CD	,
							ACQSTN_DT	,
							ACQSTN_BSNS_OUTLET_KEY	,
							ACQSTN_BSNS_OUTLET_CD	,
							CHRG_HEAD_KEY	,
							CHRG_HEAD_CD	,
							CHRGNG_PRTY_IND	,
							OTHR_CHRGNG_NBR	,
							CHRGING_ZONE_CD	,
							RTD_CLASS_CD	,
							RTNG_INFO	,
							CHRGD_AMT	,
							MARK_UP_AMT	,
							DISCOUNT_AMT	,
							TAX_AMT	,
							BLLD_AMT	,
							RVN_AMT	,
							RC_RVN_AMT	,
							NRC_RVN_AMT	,
							ECB_RVN_AMT	,
							ECB_TAX_AMT	,
							REFUND_AMT	,
							ECB_REFUND_AMT	,
							REFUND_RSN_CD	,
							ACTVTN_AMT	,
							ACTVTN_BONUS_AMT	,
							DEACTVTN_CHRG_AMT	,
							PREPAID_MAIN_ACCT_DECRMNT_AMT	,
							POSTPAID_MAIN_ACCT_DECRMNT_AMT	,
							MAIN_ACCT_BAL_AMT_BEFR_IMPACT	,
							MAIN_ACCT_BAL_AMT_AFTR_IMPACT	,
							WALLET1_KEY	,
							WALLET1_BAL_DECRMNT_AMT	,
							WALLET2_KEY	,
							WALLET2_BAL_DECRMNT_AMT	,
							WALLET3_KEY	,
							WALLET3_BAL_DECRMNT_AMT	,
							WALLET4_KEY	,
							WALLET4_BAL_DECRMNT_AMT	,
							WALLET5_KEY	,
							WALLET5_BAL_DECRMNT_AMT	,
							WALLET6_KEY	,
							WALLET6_BAL_DECRMNT_AMT	,
							WALLET7_KEY	,
							WALLET7_BAL_DECRMNT_AMT	,
							WALLET8_KEY	,
							WALLET8_BAL_DECRMNT_AMT	,
							WALLET9_KEY	,
							WALLET9_BAL_DECRMNT_AMT	,
							WALLET10_KEY	,
							WALLET10_BAL_DECRMNT_AMT	,
							LOYALTY_RANK_SCORE	,
							LOYALTY_SCORE_DT	,
							CREDIT_SCORE	,
							CREDIT_CLASS_CD	,
							CREDIT_SCORE_METHOD	,
							CREDIT_SCORE_DT	,
							RISK_IND	,
							ACCT_SEGMENT_CD	,
							ACCT_SEGMENT_DT	,
							CMPGN_CD	,
							SRC_SYS_KEY	,
							SRC_SYS_CD	,
							LOAD_DT	,
							CURR_IND	,
							WRHS_ID	

						FROM 
						(
						SELECT * FROM CDR_IN_TMP
						UNION ALL
						SELECT * FROM VASP_DEL_TMP_1
						UNION ALL
						SELECT * FROM VASP_DEL_TMP_2
						UNION ALL
						SELECT * FROM VASP_RETRY_TMP_1
						UNION ALL
						SELECT * FROM VASP_RETRY_TMP_2
						) A
					",
		"tempTable" : "ADME_RATED_OFFER_SBRP_EDR_TMP",
		"countSourceRecord" : "0"
	  }
	]
}