{
	 "description":"adme_rated_roaming_call_cdr",
	 "sqlStatements": [
      {
		"sql"      	:"
					SELECT 
						CAST(b.mo_key as STRING) as mo_key,
						CAST(NULL AS STRING) AS HOUR_KEY,
						CAST(NULL AS STRING) AS UUID,
						CAST(NULL AS STRING) AS EVT_CD,
						CAST(NULL AS BIGINT) AS EVT_SEQ_NBR,
						CAST(NULL AS BIGINT) AS PRTIAL_REC_NBR,
						CAST(NULL AS TIMESTAMP) AS EVT_START_DT,
						CAST(NULL AS TIMESTAMP) AS EVT_END_DT,
						CAST(NULL AS TIMESTAMP) AS BLLG_START_DT,
						CAST(NULL AS STRING) AS TAP_FILE_NAME,
						CAST(NULL AS TIMESTAMP) AS TAP_FILE_DT,
						CAST(NULL AS STRING) AS TAP_FILE_PREFIX_CD,
						CAST(NULL AS TIMESTAMP) AS REC_PROCESS_DT,
						CAST(NULL AS STRING) AS SWITCH_CD,
						CASE WHEN a.SERVICE_NAME ='Thue bao VMS CVQT' THEN 'O' ELSE 'I' END AS RMNG_DRCTN_CD,
						CAST(NULL AS STRING) AS TAP_DRCTN_CD,
						C.ACCT_SRVC_INSTANCE_KEY AS ACCT_SRVC_INSTANCE_KEY,
						C.SERVICE_NBR AS SERVICE_NBR,
						C.ACCT_KEY AS ACCT_KEY,
						C.BILLABLE_ACCT_KEY AS BILLABLE_ACCT_KEY,
						C.CUST_KEY AS CUST_KEY,
						C.CUST_TYP_CD AS CUST_TYP_CD,
						C.NTWK_QOS_GRP_CD AS NTWK_QOS_GRP_CD,
						C.ACTIVATION_DT AS ACCT_ACTIVATION_DT,
						C.CBS_ACTIVATION_DT AS ACCT_CBS_ACTIVATION_DT,
						C.LFCYCL_STAT_CD AS ACCT_LFCYCL_STAT_CD,
						C.ACTIVATION_DT AS SRVC_ACTIVATION_DT,
						C.CBS_ACTIVATION_DT AS SRVC_CBS_ACTIVATION_DT,
						C.LFCYCL_STAT_CD AS SRVC_LFCYCL_STAT_CD,
						C.PROD_LINE_KEY AS PROD_LINE_KEY,
						C.USAGE_PLAN_KEY AS USAGE_PLAN_KEY,
						C.USAGE_PLAN_CD AS USAGE_PLAN_CD,
						C.USAGE_PLAN_TYP_CD AS USAGE_PLAN_TYP_CD,
						C.CRM_OFFER_KEY AS OFFER_KEY,
						C.CRM_OFFER_CD AS OFFER_CD,
						CAST(NULL AS DECIMAL(20,0)) AS PROD_KEY,
						CAST(NULL AS STRING) AS PROD_CD,
						CASE 
							WHEN A.SERVICE_TYPE IN ('Goi di','Nhan cuoc goi','TB VMS goi ve VN','TB goi QTe') THEN 'VOICE'
							WHEN A.SERVICE_TYPE IN ('Gui SMS','Nhan SMS') THEN 'SMS'
							ELSE 'UNKNOWN'
						END AS EVT_CLASS_CD,
						CASE
							WHEN A.SERVICE_TYPE IN ('Goi di','Nhan cuoc goi','TB VMS goi ve VN','TB goi QTe') THEN 'VOICE_RMNG_ISD'
							WHEN A.SERVICE_TYPE IN ('Gui SMS','Nhan SMS') THEN 'SMS_RMNG_ISD'
							ELSE 'UNKNOWN'
						END AS EVT_CTGRY_CD,
						CASE
							WHEN A.SERVICE_TYPE IN ('Goi di','TB goi QTe') THEN 'VOICE_RMNG_ISD_OG'
							WHEN A.SERVICE_TYPE = 'TB VMS goi ve VN' THEN 'VOICE_RMNG_ISD_HOME_OG'
							WHEN A.SERVICE_TYPE ='Nhan cuoc goi' THEN 'VOICE_RMNG_ISD_IC'
							WHEN A.SERVICE_TYPE IN ('Gui SMS') THEN 'SMS_RMNG_ISD_OG'
							WHEN A.SERVICE_TYPE IN ('Nhan SMS') THEN 'SMS_RMNG_ISD_IC'
							ELSE 'UNKNOWN'
						END AS EVT_TYP_CD,
						CASE 
							WHEN A.SERVICE_TYPE IN ('Goi di','Nhan cuoc goi','TB VMS goi ve VN','TB goi QTe') THEN 'VOICE'
							WHEN A.SERVICE_TYPE IN ('Gui SMS','Nhan SMS') THEN 'SMS'
							ELSE 'UNKNOWN'
						END AS USAGE_TYP_CD,
						CASE
							WHEN A.SERVICE_TYPE IN ('Goi di','Nhan cuoc goi','TB VMS goi ve VN','TB goi QTe') THEN 'VOICE_RMNG_ISD'
							WHEN A.SERVICE_TYPE IN ('Gui SMS','Nhan SMS') THEN 'SMS_RMNG_ISD'
							ELSE 'UNKNOWN'
						END AS CALL_CTGRY_CD,
						CASE
							WHEN SERVICE_TYPE IN ('Goi di','TB goi QTe') THEN 'VOICE_RMNG_ISD_OG'
							WHEN SERVICE_TYPE = 'TB VMS goi ve VN' THEN 'VOICE_RMNG_ISD_HOME_OG'
							WHEN SERVICE_TYPE ='Nhan cuoc goi' THEN 'VOICE_RMNG_ISD_IC'
							WHEN SERVICE_TYPE IN ('Gui SMS') THEN 'SMS_RMNG_ISD_OG'
							WHEN SERVICE_TYPE IN ('Nhan SMS') THEN 'SMS_RMNG_ISD_IC'
							ELSE 'UNKNOWN'
						END AS CALL_TYP_CD,
						CAST(NULL AS STRING) AS CALL_STAT_CD,
						CAST(NULL AS STRING) AS CALL_TMNT_RSN_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_NBR,
						a.IMSI AS ORIGNTNG_IMSI,
						CAST(NULL AS STRING) AS ORIGNTNG_IMEI,
						d.EXTRNL_CSP_CD AS ORIGNTNG_CARRIER,
						CAST(NULL AS STRING) AS TRMNTNG_NBR,
						CAST(NULL AS STRING) AS TRMNTNG_IMSI,
						CAST(NULL AS STRING) AS TRMNTNG_IMEI,
						CAST(NULL AS STRING) AS TRMNTNG_CARRIER,
						CAST(NULL AS STRING) AS DLD_NBR,
						CAST(NULL AS BIGINT) AS ORIGNTNG_CUG_KEY,
						CAST(NULL AS BIGINT) AS TRMNTNG_CUG_KEY,
						'I' AS INTL_DMSTC_IND,
						CAST(NULL AS STRING) AS FNF_IND,
						CAST(NULL AS STRING) AS SPECIAL_DLD_NBR_IND,
						CAST(NULL AS STRING) AS TESTNG_NBR_IND,
						CASE
							WHEN SERVICE_TYPE IN ('Goi di','TB goi QTe') THEN 'O'
							WHEN SERVICE_TYPE = 'TB VMS goi ve VN' THEN 'O'
							WHEN SERVICE_TYPE ='Nhan cuoc goi' THEN 'I'
							WHEN SERVICE_TYPE IN ('Gui SMS') THEN 'O'
							WHEN SERVICE_TYPE IN ('Nhan SMS') THEN 'I' 
						END AS EVT_DRCTN_CD,
						CAST(NULL AS STRING) AS ONNET_OFFNET_IND,
						CAST(NULL AS STRING) AS REDRCTD_IND,
						CAST(NULL AS STRING) AS REDRCTD_NBR,
						CAST(NULL AS STRING) AS REDRCTD_IMSI,
						CAST(NULL AS STRING) AS REDRCTD_IMEI,
						CAST(NULL AS STRING) AS REDRCTD_CARRIER,
						CAST(NULL AS STRING) AS THRD_PRTY_HOME_CNTRY_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_MSS_CD,
						CAST(NULL AS STRING) AS TRMNTNG_MSS_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_PLMN_CD,
						CAST(NULL AS STRING) AS TRMNTNG_PLMN_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_NETWORK_TYP,
						CAST(NULL AS STRING) AS TRMNTNG_NETWORK_TYP,
						CASE WHEN A.SERVICE_NAME ='Thue bao VMS CVQT' THEN '452' ELSE CAST(D.MCC_CD AS STRING) END AS ORIGNTNG_HOME_COUNTRY_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_HOME_AREA_CD,
						CASE WHEN A.SERVICE_NAME ='Thue bao VMS CVQT' THEN '01' ELSE CAST(D.MCC_CD AS STRING) END AS ORIGNTNG_HOME_NETWORK_CD,
						CASE WHEN A.SERVICE_NAME ='Thue bao VMS CVQT' THEN CAST(D.MCC_CD AS STRING) ELSE '452' END AS ORIGNTNG_ROAM_COUNTRY_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_ROAM_AREA_CD,
						CASE WHEN A.SERVICE_NAME ='Thue bao VMS CVQT' THEN CAST(D.MCC_CD AS STRING)  ELSE  '452' END AS ORIGNTNG_ROAM_NETWORK_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_NTWK_ROUTE_CD,
						CAST(NULL AS STRING) AS TRMNTNG_HOME_COUNTRY_CD,
						CAST(NULL AS STRING) AS TRMNTNG_HOME_AREA_CD,
						CAST(NULL AS STRING) AS TRMNTNG_HOME_NETWORK_CD,
						CAST(NULL AS STRING) AS TRMNTNG_ROAM_COUNTRY_CD,
						CAST(NULL AS STRING) AS TRMNTNG_ROAM_AREA_CD,
						CAST(NULL AS STRING) AS TRMNTNG_ROAM_NETWORK_CD,
						CAST(NULL AS STRING) AS TRMNTNG_NTWK_ROUTE_CD,
						CAST(NULL AS STRING) AS FIRST_ORIGNTNG_GCI_CD,
						CAST(NULL AS STRING) AS LAST_ORIGNTNG_GCI_CD,
						CAST(NULL AS STRING) AS TRMNTNG_GCI_CD,
						CAST(NULL AS BIGINT) AS ORIGNTNG_OPRTR_KEY,
						CAST(NULL AS STRING) AS ORIGNTNG_OPRTR_CD,
						CAST(NULL AS BIGINT) AS TRMNTNG_OPRTR_KEY,
						CAST(NULL AS STRING) AS TRMNTNG_OPRTR_CD,
						CAST(NULL AS DECIMAL(27,8)) AS ADDR_LAT,
						CAST(NULL AS DECIMAL(27,8)) AS ADDR_LON,
						CAST(NULL AS STRING) AS FIRST_CELL_KEY,
						CAST(NULL AS STRING) AS FIRST_CELL_CD,
						CAST(NULL AS BIGINT) AS FIRST_CELL_SITE_KEY,
						CAST(NULL AS STRING) AS FIRST_CELL_SITE_CD,
						CAST(NULL AS STRING) AS LAST_CELL_KEY,
						CAST(NULL AS STRING) AS LAST_CELL_CD,
						CAST(NULL AS BIGINT) AS LAST_CELL_SITE_KEY,
						CAST(NULL AS STRING) AS LAST_CELL_SITE_CD,
						CAST(NULL AS BIGINT) AS NTWK_MGNT_CENTRE_KEY,
						CAST(NULL AS STRING) AS NTWK_MGNT_CENTRE_CD,
						CAST(NULL AS BIGINT) AS BSNS_RGN_KEY,
						CAST(NULL AS STRING) AS BSNS_RGN_CD,
						CAST(NULL AS BIGINT) AS BSNS_CLUSTER_KEY,
						CAST(NULL AS STRING) AS BSNS_CLUSTER_CD,
						CAST(NULL AS BIGINT) AS BSNS_MINICLUSTER_KEY,
						CAST(NULL AS STRING) AS BSNS_MINICLUSTER_CD,
						CAST(NULL AS BIGINT) AS GEO_CNTRY_KEY,
						CAST(NULL AS STRING) AS GEO_CNTRY_CD,
						CAST(NULL AS BIGINT) AS GEO_STATE_KEY,
						CAST(NULL AS STRING) AS GEO_STATE_CD,
						CAST(NULL AS STRING) AS GEO_DSTRCT_KEY,
						CAST(NULL AS STRING) AS GEO_DSTRCT_CD,
						CAST(NULL AS BIGINT) AS GEO_CITY_KEY,
						CAST(NULL AS STRING) AS GEO_CITY_CD,
						CAST(NULL AS TIMESTAMP) AS ACQSTN_DT,
						CAST(NULL AS BIGINT) AS ACQSTN_BSNS_OUTLET_KEY,
						CAST(NULL AS STRING) AS ACQSTN_BSNS_OUTLET_CD,
						CAST(NULL AS BIGINT) AS BLLG_OPRTR_KEY,
						CAST(NULL AS STRING) AS BLLG_OPRTR_CD,
						CAST(NULL AS STRING) AS BILL_GRP_CD,
						CAST(NULL AS BIGINT) AS BILL_CYCLE_KEY,
						CAST(NULL AS INTEGER) AS CHRG_HEAD_KEY,
						CAST(NULL AS STRING) AS CHRG_HEAD_CD,
						CAST(NULL AS STRING) AS CRNCY_CD,
						CAST(NULL AS STRING) AS USG_UOM_CD,
						CAST(NULL AS STRING) AS INTCONN_CRNCY_CD,
						CAST(NULL AS DECIMAL(27,8)) AS EXCHG_RATE_VAL,
						CAST(A.DURATION AS BIGINT) AS DRTN,
						CAST(A.BLOCK_DURATION AS BIGINT) AS RTD_USG,
						CAST(NULL AS BIGINT) AS FREE_USG,
						CAST(A.BLOCK_DURATION AS BIGINT) AS CHRGBL_USG,
						CAST(NULL AS BIGINT) AS INTCONN_USG,
						CAST(NULL AS STRING) AS CHRGNG_PRTY_IND,
						CAST(NULL AS STRING) AS OTHR_CHRGNG_NBR,
						CAST(NULL AS STRING) AS CHRGNG_IND,
						CAST(NULL AS STRING) AS CHRGING_ZONE_CD,
						CAST(NULL AS STRING) AS RTD_CLASS_CD,
						CAST(NULL AS STRING) AS RTNG_INFO,
						CAST(NULL AS DECIMAL(30,2)) AS CHRGD_AMT,
						CAST(NULL AS DECIMAL(30,2)) AS MARK_UP_AMT,
						CAST(NULL AS DECIMAL(30,2)) AS DISCOUNT_AMT,
						CAST(NULL AS DECIMAL(30,2)) AS TAX_AMT,
						CAST(NULL AS DECIMAL(30,2)) AS BLLD_AMT,
						CAST(NVL(A.DOANH_THU_ZONE_VND,'0') AS DECIMAL(30,2)) AS RVN_AMT,
						CAST(NULL AS DECIMAL(30,2)) AS INTERNAL_COST_AMT,
						CAST(NULL AS DECIMAL(30,2)) AS INTCONN_COST_AMT,
						CAST(NULL AS DECIMAL(30,2)) AS INTCONN_RVN_AMT,
						CAST(NULL AS STRING) AS RMNG_BANK_TYP,
						CAST(NULL AS STRING) AS RMNG_BANK_UOM_CD,
						CAST(NULL AS DECIMAL(27,8)) AS RMNG_BANK_BALANCE_BEFR_IMPACT,
						CAST(NULL AS DECIMAL(27,8)) AS RMNG_BANK_BALANCE_AFTR_IMPACT,
						CAST(NULL AS STRING) AS BLLG_STAT_RSN_CD,
						CAST(C.LOYALTY_RANK_SCORE AS DECIMAL(12,4)) AS LOYALTY_RANK_SCORE,
						CAST(C.LOYALTY_SCORE_DT AS TIMESTAMP) AS LOYALTY_SCORE_DT,
						CAST(C.CREDIT_SCORE AS DECIMAL(12,4)) AS CREDIT_SCORE,
						CAST(C.CREDIT_CLASS_CD AS STRING) AS CREDIT_CLASS_CD,
						CAST(C.CREDIT_SCORE_METHOD AS STRING) AS CREDIT_SCORE_METHOD,
						CAST(C.CREDIT_SCORE_DT AS TIMESTAMP) AS CREDIT_SCORE_DT,
						CAST(C.RISK_IND AS INTEGER) AS RISK_IND,
						CAST(NULL AS STRING) AS ACCT_SEGMENT_CD,
						CAST(NULL AS TIMESTAMP) AS ACCT_SEGMENT_DT,
						CAST(NULL AS STRING) AS CMPGN_CD,
						CAST(26 AS BIGINT) AS SRC_SYS_KEY,
						CAST('BILLING_GW' AS STRING) AS SRC_SYS_CD,
						CURRENT_TIMESTAMP() AS LOAD_DT,
						CAST('1' AS STRING) AS CURR_IND,
						CAST(1 AS INTEGER) AS WRHS_ID
					from
					(select * from mbf_datalake.ir_rpt_imsi_iot_vndate where day_key = '$day_key' and service_type != 'GPRS') a
					left join 
						mbf_bigdata.adml_day b
					on
						a.day_key = b.day_key
					left join
						(select * from mbf_bigdata.admr_account_service where day_key = '$day_key') c 
					on
						a.imsi = c.imsi
					left join
						(select * from mbf_bigdata.ADMR_EXTERNAL_CSP where day_key = '$day_key' and CSP_TYP_CD = 'IRP') d
					on
						a.tadigname = d.EXTRNL_CSP_CD
                    ",
		"tempTable"  : "adme_rated_roaming_call_cdr_tmp",
		"countSourceRecord":"0"
	  }
	]
}