{
	 "description":"ADME_RAW_DATA_CDR",
	 "sqlStatements": [
	  {
		"sql"      : "
						SELECT 
							cast (from_unixtime(unix_timestamp(a.`record_opening_time`,'E MMM dd HH:mm:ss yyyy'),'yyyyMM') as INTEGER) 				 as MO_KEY,
							cast(null as string) 																									 as UUID,
							cast(null as string) 																									 as EVT_CD,
							cast(a.LOCAL_SEQUENCE_NUMBER_v1 as bigint) 																				 as EVT_SEQ_NBR,
							cast(null as bigint) 																									 as PRTIAL_REC_NBR,
							cast(from_unixtime(unix_timestamp(a.record_opening_time,'E MMM dd HH:mm:ss yyyy'),'yyyy-MM-dd HH:mm:ss') as timestamp) 	 as EVT_START_DT,
							cast(from_unixtime(unix_timestamp(a.time_of_report,'E MMM dd HH:mm:ss yyyy'),'yyyy-MM-dd HH:mm:ss') as timestamp) 		 as EVT_END_DT,
							cast(null as timestamp) 																								 as EVT_BLLG_START_DT,
							a.ftp_filename 																											 as FILE_NAME,
							cast(null as timestamp) 																								 as FILE_DT,
							cast(null as string) 																									 as FILE_PREFIX_CD,
							cast(null as timestamp) 																								 as REC_PROCESS_DT,
							cast(null as string) 																									 as SWITCH_CD,
							b.ACCT_SRVC_INSTANCE_KEY,
							a.isdn_std as SERVICE_NBR,
							b.ACCT_KEY,
							b.BILLABLE_ACCT_KEY,
							b.CUST_KEY,
							b.CUST_TYP_CD,
							b.NTWK_QOS_GRP_CD,
							b.ACTIVATION_DT 																										 as ACCT_ACTIVATION_DT,
							b.CBS_ACTIVATION_DT 																									 as ACCT_CBS_ACTIVATION_DT,
							b.LFCYCL_STAT_CD 																										 as ACCT_LFCYCL_STAT_CD,
							b.ACTIVATION_DT 																										 as SRVC_ACTIVATION_DT,
							b.CBS_ACTIVATION_DT 																									 as SRVC_CBS_ACTIVATION_DT,
							b.LFCYCL_STAT_CD 																										 as SRVC_LFCYCL_STAT_CD,
							b.PROD_LINE_KEY,
							b.USAGE_PLAN_KEY,
							b.USAGE_PLAN_CD,
							b.USAGE_PLAN_TYP_CD,
							b.CRM_OFFER_KEY 																										 as OFFER_KEY,
							b.CRM_OFFER_CD 																											 as OFFER_CD,
							cast(null as decimal(20,0))																								 as PROD_KEY,
							cast(null as string) 																									 as PROD_CD,
							'DATA' 																													 as EVT_CLASS_CD,
							CASE WHEN a.roaming_idx = '2' THEN 'DATA_RMNG_ISD'
								 WHEN a.roaming_idx = '1' THEN 'DATA_RMNG_LOCAL'
								 WHEN a.roaming_idx = '0' THEN 'DATA_LOCAL'
							ELSE 'UNKNOWN' END 																										 as EVT_CTGRY_CD,
							CASE WHEN a.roaming_idx = '2' THEN 'DATA_RMNG_ISD'
								 WHEN a.roaming_idx = '1' THEN 'DATA_RMNG_LOCAL'
								 WHEN a.roaming_idx = '0' THEN 'DATA_LOCAL'
							ELSE 'UNKNOWN' END 																										 as EVT_TYP_CD,
							'DATA' AS USAGE_TYP_CD,
							CASE WHEN a.roaming_idx = '2' THEN 'DATA_RMNG_ISD'
								 WHEN a.roaming_idx = '1' THEN 'DATA_RMNG_LOCAL'
								 WHEN a.roaming_idx = '0' THEN 'DATA_LOCAL'
							ELSE 'UNKNOWN' END 																										 as CALL_CTGRY_CD,
							CASE WHEN a.roaming_idx = '2' THEN 'DATA_RMNG_ISD'
								 WHEN a.roaming_idx = '1' THEN 'DATA_RMNG_LOCAL'
								 WHEN a.roaming_idx = '0' THEN 'DATA_LOCAL'
							ELSE 'UNKNOWN' END 																										 as CALL_TYP_CD,
							cast(null as string) 																									 as CALL_STAT_CD,
							cast(null as string) 																									 as CALL_TMNT_RSN_CD,
							cast(null as string) 																									 as NTWK_SESSION_ID,
							cast(null as string) 																									 as BLLG_SESSION_ID,
							cast(null as string) 																									 as QOS_RQSTD,
							a.QOS_INFORMATION 																										 as QOS_NEGOTIATED,
							a.isdn_std 																												 as ORIGNTNG_NBR,
							a.SERVED_IMSI 																											 as ORIGNTNG_IMSI,
							a.SERVED_IMEISV 																										 as ORIGNTNG_IMEI,
							CASE WHEN a.roaming_idx = '2' THEN 'I' ELSE 'D' END 																	 as INTL_DMSTC_IND,
							CASE WHEN (a.roaming_idx = '1' OR a.roaming_idx = '2') THEN '1' ELSE CAST(NULL as string) END 							 as RMNG_IND,
							cast(null as string) 																									 as FNF_IND,
							cast(null as string) 																									 as TESTNG_NBR_IND,
							cast(null as string) 																									 as ONNET_OFFNET_IND,
							a.ACCESS_POINT_NAME_NETWORK_IDENTIFIER 																					 as NTWK_ACCS_POINT_IP,
							a.GGSN_ADDRESS 																											 as NTWK_SESSION_CONTROL_POINT_IP,
							a.SERVED_PDP_ADDRESS 																									 as HOST_IP,
							cast(null as string) 																									 as DOMAIN_NAME,
							cast(null as string) 																									 as ACCESSED_URL,
							cast(null as string) 																									 as DVC_OS_NAME,
							cast(null as string) 																									 as BROWSING_ACTVTY_TYP,
							a.SGSN_PLMN_IDENTIFIER_v1 																								 as ORIGNTNG_PLMN_CD,
							cast(null as string) 																									 as ORIGNTNG_NETWORK_TYP,
							SUBSTRING(a.served_imsi,1,3) 																							 as ORIGNTNG_HOME_COUNTRY_CD,
							cast(null as string) 																									 as ORIGNTNG_HOME_AREA_CD,
							SUBSTRING(a.served_imsi,4,2) 																							 as ORIGNTNG_HOME_NETWORK_CD,
							CASE WHEN (a.roaming_idx = '1' OR a.roaming_idx = '2') THEN SUBSTRING(a.served_imsi,1,3) ELSE NULL END 					 as ORIGNTNG_ROAM_COUNTRY_CD,
							cast(null as string) 																									 as ORIGNTNG_ROAM_AREA_CD,
							CASE WHEN (a.roaming_idx = '1' OR a.roaming_idx = '2') THEN SUBSTRING(a.served_imsi,4,2) ELSE NULL END 					 as ORIGNTNG_ROAM_NETWORK_CD,
							a.cell_code 																											 as FIRST_ORIGNTNG_GCI_CD,
							cast(null as string) 																									 as LAST_ORIGNTNG_GCI_CD,
							cast(null as bigint) 																									 as ORIGNTNG_OPRTR_KEY,
							cast(null as string) 																									 as ORIGNTNG_OPRTR_CD,
							cast(null as bigint) 																									 as BLLG_OPRTR_KEY,
							cast(null as string) 																									 as BLLG_OPRTR_CD,
							cast(d.ADDR_LAT as DECIMAL(27,8)) 																						 as ADDR_LAT,
							cast(d.ADDR_LON as DECIMAL(27,8)) 																						 as ADDR_LON,
							d.CELL_TYP_CD																											 as CELL_TYP_CD,
							d.CELL_KEY 																												 as FIRST_CELL_KEY,
							d.CELL_CD 																												 as FIRST_CELL_CD,
							d.CELL_SITE_KEY 																										 as FIRST_CELL_SITE_KEY,
							d.CELL_SITE_CD 																											 as FIRST_CELL_SITE_CD,
							cast(null as string) 																									 as LAST_CELL_KEY,
							cast(null as string) 																									 as LAST_CELL_CD,
							cast(null as bigint) 																									 as LAST_CELL_SITE_KEY,
							cast(null as string) 																									 as LAST_CELL_SITE_CD,
							d.NTWK_MGNT_CENTRE_KEY,
							d.NTWK_MGNT_CENTRE_CD,
							d.BSNS_RGN_KEY,
							d.BSNS_RGN_CD,
							d.BSNS_CLUSTER_KEY,
							d.BSNS_CLUSTER_CD,
							d.BSNS_MINICLUSTER_KEY,
							d.BSNS_MINICLUSTER_CD,
							d.GEO_CNTRY_KEY,
							d.GEO_CNTRY_CD,
							d.GEO_STATE_KEY,
							d.GEO_STATE_CD,
							d.GEO_DSTRCT_KEY,
							d.GEO_DSTRCT_CD,
							d.GEO_CITY_KEY,
							d.GEO_CITY_CD,
							b.ACQSTN_DT,
							b.ACQSTN_BSNS_OUTLET_KEY,
							b.ACQSTN_BSNS_OUTLET_CD,
							cast(null as string) 																									 as BILL_GRP_CD,
							cast(null as bigint) 																									 as BILL_CYCLE_KEY,
							cast(null as int) 																										 as CHRG_HEAD_KEY,
							cast(null as string) 																									 as CHRG_HEAD_CD,
							'VND' 																													 as CRNCY_CD,
							'BYTES' 																												 as USG_UOM_CD,
							'VND' 																													 as INTCONN_CRNCY_CD,
							cast(null as decimal(27,8)) 																							 as EXCHG_RATE_VAL,
							cast(a.duration as bigint) 																								 as DRTN,
							cast(null as bigint) 																									 as RTD_DRTN,
							cast(null as bigint) 																									 as FREE_DRTN,
							cast(null as bigint) 																									 as CHRGD_DRTN,
							cast(null as bigint) 																									 as INTCONN_DRTN,
							cast(a.DATA_VOLUME_FLOW_BASED_CHARGING_UPLINK + a.data_volume_fbc_downlink as bigint) 									 as TOT_FLUX,
							cast(a.DATA_VOLUME_FLOW_BASED_CHARGING_UPLINK as bigint) 																 as UP_FLUX,
							cast(a.data_volume_fbc_downlink as bigint) 																				 as DOWN_FLUX,
							'BYTES' 																												 as FLUX_UOM_CD,
							cast(null as bigint) 																									 as RTD_USG,
							cast(null as bigint) 																									 as FREE_USG,
							cast(null as bigint) 																									 as CHRGBL_USG,
							cast(null as bigint) 																									 as INTCONN_USG,
							cast(null as string) 																									 as CHRGNG_PRTY_IND,
							cast(null as string) 																									 as OTHR_CHRGNG_NBR,
							cast(null as string) 																									 as CHRGNG_IND,
							cast(null as string) 																									 as CHRGING_ZONE_CD,
							cast(null as string) 																									 as RTD_CLASS_CD,
							cast(null as string) 																									 as RTNG_INFO,
							cast(null as decimal(30,2)) 																							 as CHRGD_AMT,
							cast(null as decimal(30,2)) 																							 as MARK_UP_AMT,
							cast(null as decimal(30,2)) 																							 as DISCOUNT_AMT,
							cast(null as decimal(30,2)) 																							 as TAX_AMT,
							cast(null as decimal(30,2)) 																							 as BLLD_AMT,
							cast(null as decimal(30,2)) 																							 as RVN_AMT,
							cast(null as decimal(30,2)) 																							 as INTERNAL_COST_AMT,
							cast(null as decimal(30,2)) 																							 as INTCONN_COST_AMT,
							cast(null as decimal(30,2)) 																							 as INTCONN_RVN_AMT,
							cast(null as string) as BLLG_STAT_RSN_CD,
							b.LOYALTY_RANK_SCORE,
							b.LOYALTY_SCORE_DT,
							b.CREDIT_SCORE,
							b.CREDIT_CLASS_CD,
							b.CREDIT_SCORE_METHOD,
							b.CREDIT_SCORE_DT,
							b.RISK_IND,
							cast(null as string) 																									 as ACCT_SEGMENT_CD,
							cast(null as string) 																									 as ACCT_SEGMENT_DT,
							cast(null as string) 																									 as CMPGN_CD,
							CAST(4 as BIGINT) 																										 as SRC_SYS_KEY,
							'GGSN' 																													 as SRC_SYS_CD,
							CURRENT_TIMESTAMP() 																									 as LOAD_DT,
							'1' 																													 as CURR_IND,
							1 																														 as WRHS_ID
						FROM (
						SELECT 
							*  
						FROM mbf_datalake.flexi
						WHERE day_key = $day_key and hour_key = $hour_key 
						) a
						LEFT JOIN 
						(SELECT * FROM mbf_bigdata.admr_account_service WHERE day_key =  DATE_FORMAT(DATE_SUB(FROM_UNIXTIME(UNIX_TIMESTAMP('$day_key' , 'yyyyMMdd')), 1),'yyyyMMdd')) b
						ON a.isdn_std = b.service_nbr
						LEFT JOIN
						(SELECT * FROM mbf_bigdata.admr_cell where day_key = DATE_FORMAT(DATE_SUB(FROM_UNIXTIME(UNIX_TIMESTAMP('$day_key' , 'yyyyMMdd')), 1),'yyyyMMdd')) d
						ON a.cell_code = d.cell_key		       
					",
		"tempTable" : "ADME_RAW_DATA_CDR_TMP",
		"countSourceRecord" : "1"
	  }
	]
}