{
	 "description":"adme_rated_roaming_call_cdr",
	 "sqlStatements": [
	  {
		"sql"      	:"
					SELECT
						ROW_NUMBER() OVER (PARTITION BY x.B_SUBS ORDER BY LENGTH(y.isdn) DESC, y.exact desc) as rownum,
						x.B_SUBS AS ISDN,
						y.plmn_id as enrich_plmn_id, 
						y.BCT_PLMN_ID as BCT_ENRICH_PLMN_ID
					FROM 
					(
						select 
							*, 
							case 
								when rec_type = 'SMT' then 'M'
								when rec_type = 'SMO' then 'N'
								when rec_type = 'MTC' then 'I'
								when rec_type = 'MOC' then 'O'
								else null
							end as call_type,
							SUBSTRING(B_SUBS,1,2)  AS ISDN_LEN2,
							SUBSTRING(B_SUBS,1,3)  AS ISDN_LEN3,
							SUBSTRING(B_SUBS,1,4)  AS ISDN_LEN4,
							SUBSTRING(B_SUBS,1,5)  AS ISDN_LEN5,
							SUBSTRING(B_SUBS,1,6)  AS ISDN_LEN6, 
							SUBSTRING(B_SUBS,1,7)  AS ISDN_LEN7,
							SUBSTRING(B_SUBS,1,8)  AS ISDN_LEN8,
							SUBSTRING(B_SUBS,1,9)  AS ISDN_LEN9,
							SUBSTRING(B_SUBS,1,10) AS ISDN_LEN10,
							SUBSTRING(B_SUBS,1,11) AS ISDN_LEN11,
							SUBSTRING(B_SUBS,1,12) AS ISDN_LEN12,
							SUBSTRING(B_SUBS,1,13) AS ISDN_LEN13,
							SUBSTRING(B_SUBS,1,14) AS ISDN_LEN14,
							SUBSTRING(B_SUBS,1,15) AS ISDN_LEN15	
						from 
							mbf_datalake.nr_call_data where day_key = '$day_key'
					) x 
					join 
					(
						SELECT 
							A.FIX_PLMN_ID PLMN_ID, 
							B.PLMN_ID BCT_PLMN_ID,
							A.CALL_TYPE,
							A.EXACT,
							A.ISDN
						FROM 
						(
							SELECT 
								X.*, 
								NVL(X.PLMN_ID, Y.PLMN_ID) FIX_PLMN_ID
							FROM 
								MBF_DATALAKE.PLMN_CALLTYPE X 
							LEFT JOIN 
								(SELECT CALL_TYPE_ID, CASE WHEN PLMN_ID = '' THEN NULL ELSE PLMN_ID END AS PLMN_ID FROM MBF_DATALAKE.FIX_PLMN_CALL_TYPE) Y
							ON
						 		X.CALL_TYPE_ID = Y.CALL_TYPE_ID 
							WHERE 
						 		X.DAY_KEY = '$day_key'
						) A 
						LEFT JOIN 
						(
							SELECT 
								PLMN_ID, CALL_TYPE_ID, PLMN_NAME 
							FROM 
							(
								SELECT 
									PLMN_ID, CALL_TYPE_ID, PLMN_NAME, 
									ROW_NUMBER() OVER 
									(PARTITION BY PLMN_ID, CALL_TYPE_ID 
										ORDER BY TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(CAST(EFFECT_TO AS STRING),'yyyy-MM-dd HH:mm:ss'))) DESC NULLS FIRST, 
										TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(CAST(EFFECT_FROM AS STRING),'yyyy-MM-dd HH:mm:ss'))) ASC NULLS LAST) ROWNUM 
								FROM 
									MBF_DATALAKE.BCT_PLMN_CALL_TYPE
							) X
						 	WHERE ROWNUM = 1
						 ) B 
						 ON 
						 	A.FIX_PLMN_ID = B.PLMN_ID AND A.CALL_TYPE_ID = B.CALL_TYPE_ID
						 ORDER BY LENGTH(A.ISDN) DESC, CAST(A.EXACT AS INT) DESC
					) y
					on x.call_type = y.call_type and x.call_type is not null and 
						((B_SUBS = y.isdn and y.exact = '1') or 
					(y.exact = '0' and y.isdn in (ISDN_LEN2,ISDN_LEN3,ISDN_LEN4,ISDN_LEN5,ISDN_LEN6,ISDN_LEN7,ISDN_LEN8,ISDN_LEN9,ISDN_LEN10,ISDN_LEN11,ISDN_LEN12,ISDN_LEN13,ISDN_LEN14,ISDN_LEN15)))
                    ",
		"tempTable"  : "enrich_nr_call_data",
		"countSourceRecord":"0"
	  },
      {
		"sql"      	:"
					SELECT 
						CAST(b.mo_key as STRING) as mo_key,
						CAST(DATE_FORMAT(CAST(a.call_date AS TIMESTAMP), 'HH') AS STRING) AS HOUR_KEY,
						CAST(NULL AS STRING) AS UUID,
						CAST(NULL AS STRING) AS EVT_CD,
						CAST(NULL AS BIGINT) AS EVT_SEQ_NBR,
						CAST(NULL AS BIGINT) AS PRTIAL_REC_NBR,
						CAST(a.call_date AS TIMESTAMP) AS EVT_START_DT,
						CAST(from_unixtime(unix_timestamp(CAST(a.call_date AS TIMESTAMP))+CAST(NVL(a.CALL_DURATION, 0) AS INT)) AS TIMESTAMP) AS EVT_END_DT,
						CAST(NULL AS TIMESTAMP) AS BLLG_START_DT,
						CAST(NULL AS STRING) AS TAP_FILE_NAME,
						CAST(NULL AS TIMESTAMP) AS TAP_FILE_DT,
						CAST(NULL AS STRING) AS TAP_FILE_PREFIX_CD,
						CAST(NULL AS TIMESTAMP) AS REC_PROCESS_DT,
						CAST(NULL AS STRING) AS SWITCH_CD,
						CAST('O' AS STRING) AS RMNG_DRCTN_CD,
						CAST(NULL AS STRING) AS TAP_DRCTN_CD,
						C.ACCT_SRVC_INSTANCE_KEY AS ACCT_SRVC_INSTANCE_KEY,
						C.SERVICE_NBR AS SERVICE_NBR,
						C.ACCT_KEY AS ACCT_KEY,
						C.BILLABLE_ACCT_KEY AS BILLABLE_ACCT_KEY,
						C.CUST_KEY AS CUST_KEY,
						C.CUST_TYP_CD AS CUST_TYP_CD,
						C.NTWK_QOS_GRP_CD AS NTWK_QOS_GRP_CD,
						C.ACTIVATION_DT AS ACCT_ACTIVATION_DT,
						C.CBS_ACTIVATION_DT AS ACCT_CBS_ACTIVATION_DT,
						C.LFCYCL_STAT_CD AS ACCT_LFCYCL_STAT_CD,
						C.ACTIVATION_DT AS SRVC_ACTIVATION_DT,
						C.CBS_ACTIVATION_DT AS SRVC_CBS_ACTIVATION_DT,
						C.LFCYCL_STAT_CD AS SRVC_LFCYCL_STAT_CD,
						C.PROD_LINE_KEY AS PROD_LINE_KEY,
						C.USAGE_PLAN_KEY AS USAGE_PLAN_KEY,
						C.USAGE_PLAN_CD AS USAGE_PLAN_CD,
						C.USAGE_PLAN_TYP_CD AS USAGE_PLAN_TYP_CD,
						C.CRM_OFFER_KEY AS OFFER_KEY,
						C.CRM_OFFER_CD AS OFFER_CD,
						CAST(NULL AS DECIMAL(20,0)) AS PROD_KEY,
						CAST(NULL AS STRING) AS PROD_CD,
						CASE 
							WHEN REC_TYPE IN ('CF','MOC','MTC') THEN 'VOICE'
							WHEN REC_TYPE IN ('SMO','SMT') THEN 'SMS' 
							ELSE 'UNKNOWN'
						END AS EVT_CLASS_CD,
						CASE 
							WHEN REC_TYPE IN ('CF','MOC','MTC') THEN 'VOICE_RMNG_LOCAL'
							WHEN REC_TYPE IN ('SMO','SMT') THEN 'SMS_RMNG_LOCAL' 
							ELSE 'UNKNOWN'
						END AS EVT_CTGRY_CD,
						CASE 
							WHEN REC_TYPE IN ('CF','MOC') THEN 'VOICE_RMNG_LOCAL_OG'
							WHEN REC_TYPE IN ('MTC') THEN 'VOICE_RMNG_LOCAL_IC'
							WHEN REC_TYPE IN ('SMO') THEN 'SMS_RMNG_LOCAL_OG'
							WHEN REC_TYPE IN ('SMT') THEN 'SMS_RMNG_LOCAL_IC' 
							ELSE 'UNKNOWN'
						END AS EVT_TYP_CD,
						CASE 
							WHEN REC_TYPE IN ('CF','MOC','MTC') THEN 'VOICE'
							WHEN REC_TYPE IN ('SMO','SMT') THEN 'SMS' 
							ELSE 'UNKNOWN'
						END AS USAGE_TYP_CD,
						CASE 
							WHEN REC_TYPE IN ('CF','MOC','MTC') THEN 'VOICE_RMNG_LOCAL'
							WHEN REC_TYPE IN ('SMO','SMT') THEN 'SMS_RMNG_LOCAL' 
							ELSE 'UNKNOWN'
						END AS CALL_CTGRY_CD,
						CASE 
							WHEN REC_TYPE IN ('CF','MOC') THEN 'VOICE_RMNG_LOCAL_OG'
							WHEN REC_TYPE IN ('MTC') THEN 'VOICE_RMNG_LOCAL_IC'
							WHEN REC_TYPE IN ('SMO') THEN 'SMS_RMNG_LOCAL_OG'
							WHEN REC_TYPE IN ('SMT') THEN 'SMS_RMNG_LOCAL_IC'
							ELSE 'UNKNOWN'
						END AS CALL_TYP_CD,
						CAST(NULL AS STRING) AS CALL_STAT_CD,
						CAST(NULL AS STRING) AS CALL_TMNT_RSN_CD,
						CASE WHEN REC_TYPE IN ('CF','MOC','SMO') THEN SUBSTR(A_SUBS, 3) ELSE SUBSTR(B_SUBS, 2) END AS ORIGNTNG_NBR,
						CASE WHEN REC_TYPE IN ('CF','MOC','SMO') THEN A.IMSI ELSE NULL END AS ORIGNTNG_IMSI,
						CASE WHEN REC_TYPE IN ('CF','MOC','SMO') THEN A.IMEI ELSE NULL END AS ORIGNTNG_IMEI,
						case 
							WHEN rec_type in ('CF','MOC','SMO') then D.EXTRNL_CSP_CD
							ELSE E.EXTRNL_CSP_CD 
						END AS ORIGNTNG_CARRIER,
						case when rec_type in ('CF','MOC','SMO') then SUBSTR(B_SUBS, 2)
						ELSE SUBSTR(A_SUBS, 3) END AS TRMNTNG_NBR,
						CAST(case when rec_type in ('CF','MOC','SMO') then null ELSE A.IMSI END AS STRING) AS TRMNTNG_IMSI,
						CAST(case when rec_type in ('CF','MOC','SMO') then null  ELSE A.IMEI END AS STRING) AS TRMNTNG_IMEI,
						CAST(case when rec_type in ('CF','MOC','SMO') then E.EXTRNL_CSP_CD
							ELSE D.EXTRNL_CSP_CD 
							END AS STRING) AS TRMNTNG_CARRIER,
						CAST(NULL AS STRING) AS DLD_NBR,
						CAST(NULL AS BIGINT) AS ORIGNTNG_CUG_KEY,
						CAST(NULL AS BIGINT) AS TRMNTNG_CUG_KEY,
						'D' AS INTL_DMSTC_IND,
						CAST(NULL AS STRING) AS FNF_IND,
						CAST(NULL AS STRING) AS SPECIAL_DLD_NBR_IND,
						CAST(NULL AS STRING) AS TESTNG_NBR_IND,
						CASE 
							WHEN REC_TYPE IN ('CF','MOC') THEN 'O'
							WHEN REC_TYPE IN ('MTC') THEN 'I'
							WHEN REC_TYPE IN ('SMO') THEN 'O'
							WHEN REC_TYPE IN ('SMT') THEN 'I' 
						END AS EVT_DRCTN_CD,
						CASE 
							WHEN ENRICH_PLMN_ID = '1' THEN '1' 
							WHEN BCT_ENRICH_PLMN_ID IS NOT NULL THEN '0' 
						END AS ONNET_OFFNET_IND,
						CASE WHEN A.REC_TYPE = 'CF' THEN '20' ELSE '00' END AS REDRCTD_IND,
						CAST(NULL AS STRING) AS REDRCTD_NBR,
						CAST(NULL AS STRING) AS REDRCTD_IMSI,
						CAST(NULL AS STRING) AS REDRCTD_IMEI,
						CAST(NULL AS STRING) AS REDRCTD_CARRIER,
						CAST(NULL AS STRING) AS THRD_PRTY_HOME_CNTRY_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_MSS_CD,
						CAST(NULL AS STRING) AS TRMNTNG_MSS_CD,
						CAST(CASE WHEN A.REC_TYPE in ('MOC','SMO') THEN D.ORG_KEY ELSE E.ORG_KEY END AS STRING) AS ORIGNTNG_PLMN_CD,
						CAST(CASE WHEN A.REC_TYPE in ('MOC','SMO') THEN E.ORG_KEY ELSE D.ORG_KEY END AS STRING) AS TRMNTNG_PLMN_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_NETWORK_TYP,
						CAST(NULL AS STRING) AS TRMNTNG_NETWORK_TYP,
						CAST(NULL AS STRING) AS ORIGNTNG_HOME_COUNTRY_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_HOME_AREA_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_HOME_NETWORK_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_ROAM_COUNTRY_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_ROAM_AREA_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_ROAM_NETWORK_CD,
						CAST(NULL AS STRING) AS ORIGNTNG_NTWK_ROUTE_CD,
						CAST(NULL AS STRING) AS TRMNTNG_HOME_COUNTRY_CD,
						CAST(NULL AS STRING) AS TRMNTNG_HOME_AREA_CD,
						CAST(NULL AS STRING) AS TRMNTNG_HOME_NETWORK_CD,
						CAST(NULL AS STRING) AS TRMNTNG_ROAM_COUNTRY_CD,
						CAST(NULL AS STRING) AS TRMNTNG_ROAM_AREA_CD,
						CAST(NULL AS STRING) AS TRMNTNG_ROAM_NETWORK_CD,
						CAST(NULL AS STRING) AS TRMNTNG_NTWK_ROUTE_CD,
						CAST(NULL AS STRING) AS FIRST_ORIGNTNG_GCI_CD,
						CAST(NULL AS STRING) AS LAST_ORIGNTNG_GCI_CD,
						CAST(NULL AS STRING) AS TRMNTNG_GCI_CD,
						CAST(NULL AS BIGINT) AS ORIGNTNG_OPRTR_KEY,
						CAST(NULL AS STRING) AS ORIGNTNG_OPRTR_CD,
						CAST(NULL AS BIGINT) AS TRMNTNG_OPRTR_KEY,
						CAST(NULL AS STRING) AS TRMNTNG_OPRTR_CD,
						CAST(NULL AS DECIMAL(27,8)) AS ADDR_LAT,
						CAST(NULL AS DECIMAL(27,8)) AS ADDR_LON,
						CAST(NULL AS STRING) AS FIRST_CELL_KEY,
						CAST(NULL AS STRING) AS FIRST_CELL_CD,
						CAST(NULL AS BIGINT) AS FIRST_CELL_SITE_KEY,
						CAST(NULL AS STRING) AS FIRST_CELL_SITE_CD,
						CAST(NULL AS STRING) AS LAST_CELL_KEY,
						CAST(NULL AS STRING) AS LAST_CELL_CD,
						CAST(NULL AS BIGINT) AS LAST_CELL_SITE_KEY,
						CAST(NULL AS STRING) AS LAST_CELL_SITE_CD,
						CAST(NULL AS BIGINT) AS NTWK_MGNT_CENTRE_KEY,
						CAST(NULL AS STRING) AS NTWK_MGNT_CENTRE_CD,
						CAST(NULL AS BIGINT) AS BSNS_RGN_KEY,
						CAST(NULL AS STRING) AS BSNS_RGN_CD,
						CAST(NULL AS BIGINT) AS BSNS_CLUSTER_KEY,
						CAST(NULL AS STRING) AS BSNS_CLUSTER_CD,
						CAST(NULL AS BIGINT) AS BSNS_MINICLUSTER_KEY,
						CAST(NULL AS STRING) AS BSNS_MINICLUSTER_CD,
						CAST(NULL AS BIGINT) AS GEO_CNTRY_KEY,
						CAST(NULL AS STRING) AS GEO_CNTRY_CD,
						CAST(NULL AS BIGINT) AS GEO_STATE_KEY,
						CAST(NULL AS STRING) AS GEO_STATE_CD,
						CAST(NULL AS STRING) AS GEO_DSTRCT_KEY,
						CAST(NULL AS STRING) AS GEO_DSTRCT_CD,
						CAST(NULL AS BIGINT) AS GEO_CITY_KEY,
						CAST(NULL AS STRING) AS GEO_CITY_CD,
						CAST(NULL AS TIMESTAMP) AS ACQSTN_DT,
						CAST(NULL AS BIGINT) AS ACQSTN_BSNS_OUTLET_KEY,
						CAST(NULL AS STRING) AS ACQSTN_BSNS_OUTLET_CD,
						CAST(NULL AS BIGINT) AS BLLG_OPRTR_KEY,
						CAST(NULL AS STRING) AS BLLG_OPRTR_CD,
						CAST(NULL AS STRING) AS BILL_GRP_CD,
						CAST(NULL AS BIGINT) AS BILL_CYCLE_KEY,
						CAST(NULL AS INTEGER) AS CHRG_HEAD_KEY,
						CAST(NULL AS STRING) AS CHRG_HEAD_CD,
						CAST(NULL AS STRING) AS CRNCY_CD,
						CAST(NULL AS STRING) AS USG_UOM_CD,
						CAST(NULL AS STRING) AS INTCONN_CRNCY_CD,
						CAST(NULL AS DECIMAL(27,8)) AS EXCHG_RATE_VAL,
						CAST(A.CALL_DURATION AS BIGINT) AS DRTN,
						CAST(A.CHARGE_DURATION AS BIGINT) AS RTD_USG,
						CAST(NULL AS BIGINT) AS FREE_USG,
						CAST(NULL AS BIGINT) AS CHRGBL_USG,
						CAST(NULL AS BIGINT) AS INTCONN_USG,
						CAST(NULL AS STRING) AS CHRGNG_PRTY_IND,
						CAST(NULL AS STRING) AS OTHR_CHRGNG_NBR,
						CAST(NULL AS STRING) AS CHRGNG_IND,
						CAST(NULL AS STRING) AS CHRGING_ZONE_CD,
						CAST(NULL AS STRING) AS RTD_CLASS_CD,
						CAST(NULL AS STRING) AS RTNG_INFO,
						CAST(NULL AS DECIMAL(30,2)) AS CHRGD_AMT,
						CAST(NULL AS DECIMAL(30,2)) AS MARK_UP_AMT,
						CAST(NULL AS DECIMAL(30,2)) AS DISCOUNT_AMT,
						CAST(NULL AS DECIMAL(30,2)) AS TAX_AMT,
						CAST(NULL AS DECIMAL(30,2)) AS BLLD_AMT,
						CAST(NVL(A.AIR_CHARGE,0) AS DECIMAL(30,2)) AS RVN_AMT,
						CAST(NULL AS DECIMAL(30,2)) AS INTERNAL_COST_AMT,
						CAST(NULL AS DECIMAL(30,2)) AS INTCONN_COST_AMT,
						CAST(NULL AS DECIMAL(30,2)) AS INTCONN_RVN_AMT,
						CAST(NULL AS STRING) AS RMNG_BANK_TYP,
						CAST(NULL AS STRING) AS RMNG_BANK_UOM_CD,
						CAST(NULL AS DECIMAL(27,8)) AS RMNG_BANK_BALANCE_BEFR_IMPACT,
						CAST(NULL AS DECIMAL(27,8)) AS RMNG_BANK_BALANCE_AFTR_IMPACT,
						CAST(NULL AS STRING) AS BLLG_STAT_RSN_CD,
						CAST(C.LOYALTY_RANK_SCORE AS DECIMAL(12,4)) AS LOYALTY_RANK_SCORE,
						CAST(C.LOYALTY_SCORE_DT AS TIMESTAMP) AS LOYALTY_SCORE_DT,
						CAST(C.CREDIT_SCORE AS DECIMAL(12,4)) AS CREDIT_SCORE,
						CAST(C.CREDIT_CLASS_CD AS STRING) AS CREDIT_CLASS_CD,
						CAST(C.CREDIT_SCORE_METHOD AS STRING) AS CREDIT_SCORE_METHOD,
						CAST(C.CREDIT_SCORE_DT AS TIMESTAMP) AS CREDIT_SCORE_DT,
						CAST(C.RISK_IND AS INTEGER) AS RISK_IND,
						CAST(NULL AS STRING) AS ACCT_SEGMENT_CD,
						CAST(NULL AS TIMESTAMP) AS ACCT_SEGMENT_DT,
						CAST(NULL AS STRING) AS CMPGN_CD,
						CAST(26 AS BIGINT) AS SRC_SYS_KEY,
						CAST('BILLING_GW' AS STRING) AS SRC_SYS_CD,
						CURRENT_TIMESTAMP() AS LOAD_DT,
						CAST('1' AS STRING) AS CURR_IND,
						CAST(1 AS INTEGER) AS WRHS_ID
					FROM 
						(SELECT X.*, Y.ENRICH_PLMN_ID AS ENRICH_PLMN_ID, Y.BCT_ENRICH_PLMN_ID AS BCT_ENRICH_PLMN_ID 
						FROM (SELECT * FROM MBF_DATALAKE.NR_CALL_DATA WHERE DAY_KEY = '$day_key') X LEFT JOIN ENRICH_NR_CALL_DATA Y 
						ON X.B_SUBS = Y.ISDN AND Y.ROWNUM = 1) A
					LEFT JOIN
						MBF_BIGDATA.ADML_DAY B 
					ON
						A.DAY_KEY = B.DAY_KEY 
					LEFT JOIN
						(SELECT *, ROW_NUMBER() OVER (PARTITION BY IMSI ORDER BY CAST(LFCYCL_STAT_CD AS INT) ASC) ROW_NUM FROM MBF_BIGDATA.ADMR_ACCOUNT_SERVICE WHERE DAY_KEY = '$day_key') C 
					ON
						A.IMSI = C.IMSI AND C.ROW_NUM = 1
					LEFT JOIN 
						(SELECT * FROM MBF_BIGDATA.ADMR_EXTERNAL_CSP WHERE DAY_KEY = '$day_key' AND CSP_TYP_CD = 'MOBILE') D
					ON 
						A.PLMN_ID = D.ORG_KEY
					LEFT JOIN 
						(SELECT * FROM MBF_BIGDATA.ADMR_EXTERNAL_CSP WHERE DAY_KEY = '$day_key' AND CSP_TYP_CD = 'MOBILE') E
					ON 
						a.ENRICH_PLMN_ID = e.PLMN_CD
                    ",
		"tempTable"  : "adme_rated_roaming_call_cdr_tmp",
		"countSourceRecord":"0"
	  }
	]
}