{
	 "description":"ADME_RATED_OCS_EVOUCHER",
	 "sqlStatements": [
	 
	 {
		"sql"      	:"
						SELECT 
							*
						FROM
						(
							SELECT * ,
							ROW_NUMBER() OVER(PARTITION BY A.ACC_REF, A.TRANSACTION_ID ORDER BY ABS(A.TIME_SA - B.TIME_SB),B.TIME_SB - A.TIME_SA ) AS ROW_NUM
							FROM
							(
								SELECT TRANSACTION_ID, ACC_REF,SCRPREF AMOUNT, concat_ws(' ',date_use,time_use) dt_use, UNIX_TIMESTAMP(concat_ws(' ',date_use,time_use),'dd/MM/yyyy HH:mm:ss') as TIME_SA, SCNUM, ftp_filename 
								FROM MBF_DATALAKE.EVOUCHER_HN WHERE DAY_KEY = '$day_key'
							) A
							LEFT JOIN
							(
								SELECT UNIX_TIMESTAMP(EVT_START_DT,'yyyy-MM-dd HH:mm:ss') AS TIME_SB , SERVICE_NBR AS ISDN ,
									FIRST_CELL_KEY AS CELL_ID,FIRST_CELL_CD,FIRST_CELL_SITE_KEY,FIRST_CELL_SITE_CD,CELL_TYP_CD FIRST_CELL_TYP_CD,NTWK_MGNT_CENTRE_KEY ,NTWK_MGNT_CENTRE_CD ,
									BSNS_RGN_KEY,BSNS_RGN_CD,BSNS_CLUSTER_KEY,BSNS_CLUSTER_CD,BSNS_MINICLUSTER_KEY ,BSNS_MINICLUSTER_CD ,GEO_CNTRY_KEY,GEO_CNTRY_CD,
									GEO_STATE_KEY,GEO_STATE_CD,GEO_DSTRCT_KEY,GEO_DSTRCT_CD,GEO_CITY_KEY,GEO_CITY_CD
									
								FROM MBF_BIGDATA.ADME_RAW_DATA_CDR 
								WHERE DAY_KEY = '$day_key' AND FIRST_CELL_KEY IS NOT NULL
								UNION ALL 
								SELECT UNIX_TIMESTAMP(EVT_START_DT,'yyyy-MM-dd HH:mm:ss') AS TIME_SB, SERVICE_NBR AS ISDN,
									FIRST_CELL_KEY AS CELL_ID,FIRST_CELL_CD,FIRST_CELL_SITE_KEY,FIRST_CELL_SITE_CD, FIRST_CELL_TYP_CD,NTWK_MGNT_CENTRE_KEY ,NTWK_MGNT_CENTRE_CD ,
									BSNS_RGN_KEY,BSNS_RGN_CD,BSNS_CLUSTER_KEY,BSNS_CLUSTER_CD,BSNS_MINICLUSTER_KEY ,BSNS_MINICLUSTER_CD ,GEO_CNTRY_KEY,GEO_CNTRY_CD,
									GEO_STATE_KEY,GEO_STATE_CD,GEO_DSTRCT_KEY,GEO_DSTRCT_CD,GEO_CITY_KEY,GEO_CITY_CD
									
								FROM MBF_BIGDATA.ADME_RAW_GSM_CALL_CDR  
								WHERE day_key = '$day_key' AND FIRST_CELL_KEY IS NOT NULL
							) B ON A.ACC_REF = B.ISDN
							
						) C WHERE C.ROW_NUM = 1
					 ",
		"tempTable"  : "EVOUCHER_ENRICH_TMP",
		"countSourceRecord":"0"
	  },
	  {
		"sql"      	:"
					SELECT *,
						ROW_NUMBER() OVER(PARTITION BY ACC_REF ORDER BY cast(unix_timestamp(DT_USE,'dd/MM/yyyy HH:mm:ss') as bigint)) AS ROW_NUM_1
					
					FROM
					EVOUCHER_ENRICH_TMP
					 ",
		"tempTable"  : "EVOUCHER_ENRICH_TMP_1",
		"countSourceRecord":"0"
	  },
	  {
	  	"sql"      	:"
					SELECT *, 
					ROW_NUMBER() OVER(PARTITION BY SO_MUA ORDER BY  cast(unix_timestamp(ngay_thang_nam,'dd/MM/yyyy HH:mm:ss') as bigint)) AS ROW_NUM 
					FROM MBF_DATALAKE.EVS WHERE DAY_KEY = '$day_key'
					 ",
		"tempTable"  : "EVS_TMP",
		"countSourceRecord":"0"
	  },
		{	   	  
		"sql"      	:"
					SELECT 
						cast(from_unixtime(unix_timestamp(CC.DT_USE,'dd/MM/yyyy HH:mm:ss'),'yyyyMM')	as integer) as	MO_KEY,
						cast(from_unixtime(unix_timestamp(CC.DT_USE,'dd/MM/yyyy HH:mm:ss'),'HH')	as integer) as	HOUR_KEY,
						cast(null as string)	as	UUID,
						cast(CC.transaction_id as string) as OCS_TXN_CD,
						cast(from_unixtime(unix_timestamp(CC.DT_USE,'dd/MM/yyyy HH:mm:ss'))	as timestamp)		as	OCS_TXN_DT,
						cast(null as timestamp)	as	BLLG_START_DT,
						CC.ftp_filename 			as	FILE_NAME,
						cast(null as timestamp)	as	FILE_DT,
						cast(null as string)	as	FILE_PREFIX_CD,
						cast(from_unixtime(unix_timestamp(CC.DT_USE,'dd/MM/yyyy HH:mm:ss'))	as timestamp)		AS REC_PROCESS_DT,
						cast(null as string)	as	OCS_SWITCH_CD,
						D.ACCT_SRVC_INSTANCE_KEY as	ACCT_SRVC_INSTANCE_KEY,
						CC.ACC_REF	 			as SERVICE_NBR,
						D.ACCT_KEY 				as ACCT_KEY,
						D.BILLABLE_ACCT_KEY 	as BILLABLE_ACCT_KEY,
						D.CUST_KEY 			AS CUST_KEY,
						D.CUST_TYP_CD 			AS CUST_TYP_CD,
						D.NTWK_QOS_GRP_CD 		AS NTWK_QOS_GRP_CD,
						D.ACTIVATION_DT 		AS ACCT_ACTIVATION_DT,
						D.CBS_ACTIVATION_DT		AS ACCT_CBS_ACTIVATION_DT,
						D.LFCYCL_STAT_CD 		AS ACCT_LFCYCL_STAT_CD,
						D.ACTIVATION_DT 		AS SRVC_ACTIVATION_DT,
						D.CBS_ACTIVATION_DT		AS SRVC_CBS_ACTIVATION_DT,
						D.LFCYCL_STAT_CD 		AS SRVC_LFCYCL_STAT_CD,
						D.PROD_LINE_KEY 		AS PROD_LINE_KEY,
						D.USAGE_PLAN_KEY 		AS USAGE_PLAN_KEY,
						D.USAGE_PLAN_CD 		AS USAGE_PLAN_CD,
						D.USAGE_PLAN_TYP_CD 	AS USAGE_PLAN_TYP_CD,
						D.CORPORATE_IND			AS CORPORATE_IND,
						D.CRM_OFFER_KEY	    	AS OFFER_KEY,
						D.CRM_OFFER_CD		    AS OFFER_CD,
						CAST(NULL AS DECIMAL(20,0)) AS PROD_KEY,
						CAST(NULL AS STRING) 	AS 	PROD_CD,
						'RECHARGE' 				AS EVT_CLASS_CD,
						'RCHRG_TOPUP' 			AS EVT_CTGRY_CD,
						(CASE
							WHEN LENGTH (TRANSLATE (G.SO_BAN, '_0123456789', '_')) = 0
							THEN 'RCHRG_TOPUP_EZ' 
							ELSE 'RCHRG_TOPUP_AIRTIME' 
						END) 					AS EVT_TYP_CD,
						CAST(NULL AS STRING) 	AS CHNL_TYP_CD,
						CAST(NULL AS STRING) 	AS CHNL_CD,
						'ETOPUP' 				AS OCS_TXN_TYP_CD,
						CAST(NULL AS STRING) 	AS BAL_TRNSFR_TYP_CD,
						'Successful' 			AS OCS_TXN_STAT_CD,
						'0' 					AS OCS_TXN_STAT_RSN_CD,
						(SELECT  cast(EXTRNL_CSP_KEY as integer) FROM MBF_BIGDATA.ADMR_EXTERNAL_CSP where EXTRNL_CSP_CD = 'VNMMO' AND DAY_KEY = '$day_key')	AS BLLG_OPRTR_KEY,
						'VNMMO' 				AS BLLG_OPRTR_CD,
						CAST(NULL AS STRING) 	AS TRNSFEROR_OCS_ACCT_REF,
						cast(NULL as integer) 		AS TRNSFEROR_BSNS_OUTLET_KEY,
						CAST(NULL AS STRING) 		AS TRNSFEROR_BSNS_OUTLET_CD,
						CAST(NULL AS STRING) 		AS TRNSFEROR_SERVICE_NBR,
						CAST(NULL AS STRING) 	AS TRNSFEREE_OCS_ACCT_REF,
						cast(D.ACQSTN_BSNS_OUTLET_KEY as integer) 	AS TRNSFEREE_BSNS_OUTLET_KEY,
						D.ACQSTN_BSNS_OUTLET_CD AS TRNSFEREE_BSNS_OUTLET_CD,
						D.BUSINESS_KEY 			AS TRNSFEREE_SERVICE_NBR,
						CAST(NULL AS STRING) 	AS VCHR_BATCH_NBR,
						CC.SCNUM 				AS VCHR_SRL_NBR_FROM,
						CC.SCNUM 				AS VCHR_SRL_NBR_TO,
						CAST(NULL AS STRING) 	AS CARD_GRP_INFO,
						CAST(NULL AS STRING) 	AS VCHR_PRTNR_INFO,
						CAST(NULL AS STRING) 	AS REF_INVOICE_NBR,
						CAST(NULL AS TIMESTAMP) AS REF_INVOICE_DT,
						cast(CC.AMOUNT as decimal(27,8)) AS OCS_TXN_AMT,
						CAST(NULL AS decimal(27,8)) AS RVN_AMT,
						CAST(NULL AS decimal(27,8)) AS TAX_AMT,
						cast(CC.AMOUNT as decimal(27,8)) AS FACE_VALUE_AMT,
						'0' 					AS PYMT_IND,
						CAST(NULL AS decimal(27,8)) AS COMMISSION_AMT,
						CAST(NULL AS decimal(27,8)) AS TRNSFEROR_OCS_ACCT_BAL_BFR,
						CAST(NULL AS decimal(27,8)) AS TRNSFEROR_OCS_ACCT_BAL_AFTR,
						CAST(NULL AS decimal(27,8)) AS TRNSFEREE_OCS_ACCT_BAL_BFR,
						CAST(NULL AS decimal(27,8)) AS TRNSFEREE_OCS_ACCT_BAL_AFTR,
						CAST(NULL AS STRING) 	AS CHARGING_REQUEST_INFO,
						CAST(NULL AS STRING) 	AS CHARGING_RESPONSE_INFO,
						CAST(NULL AS STRING) 	AS ORIGINAL_GCI_CD,
						CAST(NULL AS decimal(27,8)) AS ADDR_LAT,
						CAST(NULL AS decimal(27,8)) AS ADDR_LON,
						(CASE WHEN CC.CELL_ID IS NULL  THEN S.LAST_ACTIVITY_CELL_KEY ELSE CC.CELL_ID END) 				AS CELL_KEY,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.CELL_CD ELSE CC.FIRST_CELL_CD END) 						AS CELL_CD,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.CELL_SITE_KEY ELSE CC.FIRST_CELL_SITE_KEY END)			AS CELL_SITE_KEY,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.CELL_SITE_CD  ELSE CC.FIRST_CELL_SITE_CD END)				AS CELL_SITE_CD,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.CELL_TYP_CD  ELSE CC.FIRST_CELL_TYP_CD END)				AS CELL_TYP_CD,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.NTWK_MGNT_CENTRE_KEY ELSE CC.NTWK_MGNT_CENTRE_KEY END) 	AS NTWK_MGNT_CENTRE_KEY,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.NTWK_MGNT_CENTRE_CD ELSE CC.NTWK_MGNT_CENTRE_CD END)		AS NTWK_MGNT_CENTRE_CD,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.BSNS_RGN_KEY ELSE CC.BSNS_RGN_KEY END)					AS BSNS_RGN_KEY,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.BSNS_RGN_CD ELSE CC.BSNS_RGN_CD END)						AS BSNS_RGN_CD,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.BSNS_CLUSTER_KEY ELSE CC.BSNS_CLUSTER_KEY END)			AS BSNS_CLUSTER_KEY,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.BSNS_CLUSTER_CD ELSE CC.BSNS_CLUSTER_CD END)				AS BSNS_CLUSTER_CD,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.BSNS_MINICLUSTER_KEY ELSE CC.BSNS_MINICLUSTER_KEY END) 	AS BSNS_MINICLUSTER_KEY,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.BSNS_MINICLUSTER_CD ELSE CC.BSNS_MINICLUSTER_CD END)		AS BSNS_MINICLUSTER_CD,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.GEO_CNTRY_KEY ELSE CC.GEO_CNTRY_KEY END)					AS GEO_CNTRY_KEY,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.GEO_CNTRY_CD ELSE CC.GEO_CNTRY_CD END)					AS GEO_CNTRY_CD,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.GEO_STATE_KEY ELSE CC.GEO_STATE_KEY END)					AS GEO_STATE_KEY,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.GEO_STATE_CD ELSE CC.GEO_STATE_CD END)					AS GEO_STATE_CD,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.GEO_DSTRCT_KEY ELSE CC.GEO_DSTRCT_KEY END)				AS GEO_DSTRCT_KEY,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.GEO_DSTRCT_CD ELSE CC.GEO_DSTRCT_CD END)					AS GEO_DSTRCT_CD,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.GEO_CITY_KEY ELSE CC.GEO_CITY_KEY END)					AS GEO_CITY_KEY,
						(CASE WHEN CC.CELL_ID IS NULL  THEN E.GEO_CITY_CD ELSE CC.GEO_CITY_CD END)						AS GEO_CITY_CD,
						D.ACQSTN_DT 			AS ACQSTN_DT,
						D.ACQSTN_BSNS_OUTLET_KEY AS ACQSTN_BSNS_OUTLET_KEY,
						D.ACQSTN_BSNS_OUTLET_CD AS ACQSTN_BSNS_OUTLET_CD,
						D.LOYALTY_RANK_SCORE 	AS LOYALTY_RANK_SCORE,
						D.LOYALTY_SCORE_DT 		AS LOYALTY_SCORE_DT,
						D.CREDIT_SCORE 			AS CREDIT_SCORE,
						D.CREDIT_CLASS_CD 		AS CREDIT_CLASS_CD,
						D.CREDIT_SCORE_METHOD 	AS CREDIT_SCORE_METHOD,
						D.CREDIT_SCORE_DT 		AS CREDIT_SCORE_DT,
						D.RISK_IND 				AS RISK_IND,
						CAST(NULL AS STRING)	AS ACCT_SEGMENT_CD,
						CAST(NULL AS STRING) 	AS ACCT_SEGMENT_DT,
						CAST(NULL AS STRING) 	AS CMPGN_CD,
						3						AS SRC_SYS_KEY,
						'Evoucher'				AS SRC_SYS_CD,
						current_timestamp()		AS LOAD_DT,
						'1' 					AS CURR_IND,
						1 						AS WRHS_ID
					FROM
					EVOUCHER_ENRICH_TMP_1 CC	
					LEFT JOIN EVS_TMP G ON CC.ACC_REF = G.SO_MUA AND CC.ROW_NUM_1 = G.ROW_NUM 
					LEFT JOIN MBF_BIGDATA.ADMR_ACCOUNT_SERVICE D ON CC.ACC_REF = D.SERVICE_NBR AND D.DAY_KEY = '$day_key'
					LEFT JOIN MBF_BIGDATA.ADMD_SERVICE_TWIN_CLM_ACTVTY S ON CC.ACC_REF = S.SERVICE_NBR AND CC.CELL_ID IS NULL AND S.DAY_KEY =  DATE_FORMAT(DATE_ADD(FROM_UNIXTIME(UNIX_TIMESTAMP('$day_key','yyyyMMdd')),-1),'yyyyMMdd')
					LEFT JOIN MBF_BIGDATA.ADMR_CELL E ON E.CELL_ID = S.LAST_ACTIVITY_CELL_KEY AND E.DAY_KEY = DATE_FORMAT(DATE_ADD(FROM_UNIXTIME(UNIX_TIMESTAMP('$day_key','yyyyMMdd')),-1),'yyyyMMdd')
					
				 ",
		"tempTable"  : "ADME_RATED_OCS_EVOUCHER_TMP",
		"countSourceRecord":"0"
	  }   	  
	]
}