{
	 "description":"ADME_PCRF_SUBSCRIPTION_UDR",
	 "createBy":"ManhNT",
	 "createDate":"01/08/2021",
	 "modifiedBy":"",
	 "modifiedDate":"",
	 "sqlStatements": [
	  {
		"sql"      : "
						SELECT 
							CAST(SUBSTRING('20210601',5,2) AS INTEGER )  																AS MO_KEY,
							CAST(NULL AS INTEGER) 																						AS HOUR_KEY,
							CAST(NULL AS STRING) 																						AS UUID,
							CAST(NULL AS TIMESTAMP) 																					AS BLLG_START_DT,
							''																											AS FILE_NAME,
							CAST(NULL AS TIMESTAMP) 																					AS FILE_DT,
							CAST(NULL AS STRING) 																						AS FILE_PREFIX_CD,
							CAST(NULL AS TIMESTAMP) 																					AS REC_PROCESS_DT,
							CAST(NULL AS STRING) 																						AS PCRF_SWITCH_CD,
							CAST(NULL AS INTEGER) 																						AS NTWK_MGNT_CENTRE_KEY,
							CAST(NULL AS STRING) 																						AS NTWK_MGNT_CENTRE_CD,
							B.ACCT_SRVC_INSTANCE_KEY 																					AS ACCT_SRVC_INSTANCE_KEY,
							B.ACCT_KEY 																									AS ACCT_KEY,
							B.BILLABLE_ACCT_KEY																							AS BILLABLE_ACCT_KEY,
							B.CUST_KEY 																									AS CUST_KEY,
							B.CUST_TYP_CD 																								AS CUST_TYP_CD,
							B.NTWK_QOS_GRP_CD							     															AS NTWK_QOS_GRP_CD,
							B.ACTIVATION_DT 															    							AS ACCT_ACTIVATION_DT,
							B.CBS_ACTIVATION_DT 														    							AS ACCT_CBS_ACTIVATION_DT,
							B.LFCYCL_STAT_CD 														        							AS ACCT_LFCYCL_STAT_CD,
							CAST(NULL AS TIMESTAMP) 																					AS SRVC_ACTIVATION_DT,
							CAST(NULL AS TIMESTAMP) 																					AS SRVC_CBS_ACTIVATION_DT,
							CAST(NULL AS STRING) 																						AS SRVC_LFCYCL_STAT_CD,
							B.PROD_LINE_KEY 																							AS PROD_LINE_KEY,
							B.USAGE_PLAN_KEY 																							AS USAGE_PLAN_KEY,
							B.USAGE_PLAN_CD																								AS USAGE_PLAN_CD,
							B.USAGE_PLAN_TYP_CD																							AS USAGE_PLAN_TYP_CD,
							B.CRM_OFFER_KEY																								AS OFFER_KEY,
							B.CRM_OFFER_CD 																								AS OFFER_CD,
							CAST(NULL AS STRING) 																						AS PROD_KEY,
							CAST(NULL AS STRING) 																						AS PROD_CD,
							'DATA' 																										AS EVT_CLASS_CD,
							'DATA_PACK_SBRP' 																							AS EVT_CTGRY_CD,
							'DATA_PACK_ACTVTN' 																							AS EVT_TYP_CD,
							'DATA' 																										AS USAGE_TYP_CD,
							CAST(NULL AS STRING) 																						AS BILL_GRP_CD,
							CAST(NULL AS INTEGER) 																						AS BILL_CYCLE_KEY,
							B.SERVICE_NBR 																								AS SERVICE_NBR,
							NVL(A.HOMESRVZONE, CAST(NULL AS STRING))   																	AS HOME_SERVICE_ZONE_CD,
							CAST(NULL AS STRING) 																						AS PCRF_SUBSCRIBER_PROFL_CD,
							CAST(NULL AS STRING) 																						AS PCRF_PROFL_CTGRY_CD,
							CASE WHEN (A.SERVICENAME IS NULL OR A.SERVICENAME == '') THEN CAST(NULL AS STRING) ELSE  A.SERVICENAME END	AS PCRF_SRVC_PROFL_CD,
							CAST(NULL AS STRING) 																						AS PCRF_BANK_CD,
							CAST(NULL AS STRING) 																						AS PCRF_BANK_TYP,
							'BYTES' 																									AS PCRF_BANK_UOM_CD,							
							CAST(UNIX_TIMESTAMP(A.SUBSCRIBEDATETIME,'yyyyMMddHHmmss') AS TIMESTAMP)         							AS PCRF_BANK_SBRP_DT,
							CAST(UNIX_TIMESTAMP(A.VALIDFROMDATETIME,'yyyyMMddHHmmss') AS TIMESTAMP)         							AS PCRF_BANK_VLDT_START_DT,
							CAST(UNIX_TIMESTAMP(A.EXPIREDDATETIME,'yyyyMMddHHmmss') AS TIMESTAMP)           							AS PCRF_BANK_VLDT_EXPIRY_DT,
							CAST(A.INITIALVALUE AS DECIMAL(30,4))																		AS PCRF_BANK_INITIAL_VALUE,
							CAST(A.CONSUMPTION AS DECIMAL(30,4))																		AS PCRF_BANK_USED,
							CAST(A.BALANCE AS DECIMAL(30,4))																			AS PCRF_BANK_BALANCE,							
							CASE WHEN (A.STATUS IS NULL OR A.STATUS == '') THEN CAST(NULL AS STRING) ELSE  A.STATUS END					AS PCRF_BANK_STAT_CD,
							B.ACQSTN_DT 																								AS ACQSTN_DT,
							B.ACQSTN_BSNS_OUTLET_KEY 																					AS ACQSTN_BSNS_OUTLET_KEY,
							B.ACQSTN_BSNS_OUTLET_CD																						AS ACQSTN_BSNS_OUTLET_CD,
							B.LOYALTY_RANK_SCORE 																						AS LOYALTY_RANK_SCORE,
							B.LOYALTY_SCORE_DT 																							AS LOYALTY_SCORE_DT,
							B.CREDIT_SCORE 																								AS CREDIT_SCORE,
							B.CREDIT_CLASS_CD 																							AS CREDIT_CLASS_CD,
							B.CREDIT_SCORE_METHOD 																						AS CREDIT_SCORE_METHOD,
							B.CREDIT_SCORE_DT 																							AS CREDIT_SCORE_DT,
							B.RISK_IND 																									AS RISK_IND,
							CAST(NULL AS STRING) 																						AS ACCT_SEGMENT_CD,
							CAST(NULL AS STRING) 																						AS ACCT_SEGMENT_DT,
							CAST(NULL AS STRING) 																						AS CMPGN_CD,
							17 																			    							AS SRC_SYS_KEY,
							'PCRF' 																										AS SRC_SYS_CD,
							CURRENT_TIMESTAMP()	 								       													AS LOAD_DT,
							'1'																											AS CURR_IND,							
							 1								    				       													AS WRHS_ID		
						FROM MBF_DATALAKE.DUMP_PCRF A
						LEFT JOIN MBF_BIGDATA.ADMR_ACCOUNT_SERVICE B ON SUBSTRING(A.MSISDN,3) = B.SERVICE_NBR  AND B.DAY_KEY = '$day_key'
						WHERE A.DAY_KEY = '$day_key' 
					 ",
		"tempTable" : "ADME_PCRF_SUBSCRIPTION_UDR_TMP",
		"countSourceRecord" : "1"		
	  }
	]
}